import { normalizeFlowLocale } from "../lib/flow-locale.js";

const STRINGS = {
  en: {
    private: "Private",
    loginSub: "Fast Answer console. The password stays on the server.",
    locked: "Session locked — enter the password again.",
    password: "Password",
    enter: "Enter",
    backGame: "Back to the game",
    weekLine: "Week {week} · locale {locale} · review, metrics, profiles, rooms.",
    play: "Play",
    logout: "Log out",
    localeGroup: "Locale",
    tab_console: "Console",
    tab_metrics: "Metrics",
    tab_queue: "Queue",
    tab_profiles: "Profiles",
    tab_rooms: "Rooms",
    tab_bank: "Bank",
    tab_archive: "Archives",
    tab_topic: "Topics",
    tab_reject: "Reject log",
    loadingArchive: "Loading archive…",
    backArchives: "← Archives",
    backMonths: "← All months",
    placementTitle: "Placement",
    placementNote: "Dojo placement bank. Replace a question here. The old one goes to the reject log.",
    monthlyTitle: "Monthly archive",
    monthlyNote: "Published weeks for this language. Replace keeps one straight swap and logs the question that left.",
    questions: "questions",
    weekOne: "week",
    weekMany: "weeks",
    updated: "updated",
    noWeeks: "No weeks archived this month.",
    noPlacement: "No placement pack bundled.",
    emptyArchive: "Archive empty — publish a week to seed it.",
    placementTag: "placement",
    filterPh: "Filter topic or question…",
    noFilter: "No questions in this filter.",
    potential: "Potential replacement",
    potentialShort: "Next",
    readyShort: "Ready",
    readyCount: "ready",
    replace: "Replace",
    noReplacement: "No potential replacement is ready yet.",
    replacedLogged: "Replaced {id}. That question is in the reject log.",
    countsLine: "{counts} · {n} questions",
    rejectLogTitle: "Reject log",
    rejectLogNote: "A replaced question lands here. The archive no longer rejects or regenerates on its own.",
    refreshLog: "Refresh log",
    downloadLog: "Download log",
    logTitle: "Log",
    noRejected: "No rejected questions yet.",
    replacementOf: "Replacement {id}",
    logged: "In the log",
    loadingLog: "Loading the log…",
    downloadedLog: "Rejected-question log downloaded.",
    metrics: "Metrics",
    pending: "pending",
    approved: "approved",
    rejected: "rejected",
    approve: "Approve",
    reject: "Reject",
    pendingBtn: "Pending",
    noQuestions: "No questions in filter.",
    addTopic: "Add topic",
    topicNote: "Adds to this Flow instance. Persist in studio for durability.",
    topics: "Topics",
    easyOnly: "easy only",
    awaiting: "Awaiting review",
    rejectedCard: "Rejected",
    regenCard: "Reject log",
    profilesCard: "Profiles",
    roomsCard: "Open rooms",
    refreshing: "Refreshing banks, profiles, and rooms…",
    countsNote: "Counts cover the weekly bank and Dojo placement for this locale, plus activated profiles and open rooms.",
    glowTitle: "Glow",
    glowNote: "GMGbrand links Flow out to the house game room — Fast Answer, SunFun, and Last Call on the glowing cards.",
    openGlow: "Open Glow",
    openRooms: "Open rooms",
    refreshRooms: "Refresh rooms",
    roomsNote: "Same list as Join TV. A room appears when its TV link is open. Delete removes it for everyone.",
    noRooms: "No open rooms.",
    delete: "Delete",
    deletedRoom: "Deleted room {code}.",
    reviewQueue: "Review queue",
    refresh: "Refresh",
    queueNote: "Questions awaiting review or already in the reject log — weekly bank and Dojo placement, locale {locale}.",
    waitingNone: "No questions are waiting for review.",
    banksMissing: "Week and placement banks did not load.",
    rejection: "Rejection",
    noRejectedQs: "No rejected questions.",
    inLog: "In the reject log",
    replacedBy: "Replacement: {id}",
    noneLogged: "No questions are in the reject log.",
    profiles: "Profiles",
    downloadMail: "Download mailing list",
    mailLine: "{n} activated · {n} emails. The CSV is every email on this list.",
    mailOne: "{n} activated · {n} email. The CSV is every email on this list.",
    name: "Name",
    email: "Email",
    activated: "Activated",
    status: "Status",
    active: "Active",
    noProfiles: "No activated profiles yet. They appear when a player taps Enter Profile.",
    loadingQueue: "Loading questions, profiles, and rooms…",
    mailDownloaded: "Mailing list downloaded.",
    localeSet: "Locale {locale}",
    topicAdded: "Topic added (runtime).",
    durable: "Durable path: handoff, then git push. Each language has its own archive under banks/archive.",
    bankReview: "Weekly bank review",
    noneWeek: "None this week.",
    louisBlurb: "Q&A safeguard · ages 13–16. Child psychology and human behaviour: fun, happiness, and a non-threatening shape.",
    louisCount: "{shaped} structured · {held} held. Notes can go to {mail}.",
    comedyBlurb: "Q&A comedy bot · week {week}. New funny questions, then the highest rated.",
    viralWeek: "Viral this week",
    highest: "Highest rated",
    activatedProfiles: "Activated profiles",
    profilesNote: "Players who tap Enter Profile are activated here. The mailing list is every email on this list.",
    analytics: "Analytics",
    lastPublish: "Last publish",
    notYet: "not yet",
    publishWeek: "Publish week",
    tier_all: "all",
    tier_easy: "easy",
    tier_hard: "hard",
    tier_difficult: "difficult",
    tier_extreme: "extreme",
    tier_finale: "finale",
  },
  fr: {
    private: "Privé",
    loginSub: "Console Fast Answer. Le mot de passe reste sur le serveur.",
    locked: "Session verrouillée — entrez le mot de passe à nouveau.",
    password: "Mot de passe",
    enter: "Entrer",
    backGame: "Retour au jeu",
    weekLine: "Semaine {week} · langue {locale} · revue, mesures, profils, salles.",
    play: "Jouer",
    logout: "Se déconnecter",
    localeGroup: "Langue",
    tab_console: "Console",
    tab_metrics: "Mesures",
    tab_queue: "File",
    tab_profiles: "Profils",
    tab_rooms: "Salles",
    tab_bank: "Banque",
    tab_archive: "Archives",
    tab_topic: "Thèmes",
    tab_reject: "Journal des rejets",
    loadingArchive: "Chargement des archives…",
    backArchives: "← Archives",
    backMonths: "← Tous les mois",
    placementTitle: "Classement",
    placementNote: "Banque de classement du Dojo. Remplacez une question ici. L'ancienne va dans le journal des rejets.",
    monthlyTitle: "Archives du mois",
    monthlyNote: "Semaines publiées pour cette langue. Remplacer échange la question et l'inscrit au journal des rejets.",
    questions: "questions",
    weekOne: "semaine",
    weekMany: "semaines",
    updated: "mise à jour",
    noWeeks: "Aucune semaine archivée ce mois-ci.",
    noPlacement: "Aucun classement n'est inclus.",
    emptyArchive: "Archives vides — publiez une semaine pour les remplir.",
    placementTag: "classement",
    filterPh: "Filtrer le thème ou la question…",
    noFilter: "Aucune question dans ce filtre.",
    potential: "Remplacement proposé",
    potentialShort: "Proposé",
    readyShort: "Prêt",
    readyCount: "prêtes",
    replace: "Remplacer",
    noReplacement: "Aucun remplacement proposé pour le moment.",
    replacedLogged: "{id} est remplacée. Cette question est dans le journal des rejets.",
    countsLine: "{counts} · {n} questions",
    rejectLogTitle: "Journal des rejets",
    rejectLogNote: "Une question remplacée arrive ici. Les archives ne rejettent plus et ne régénèrent plus.",
    refreshLog: "Actualiser le journal",
    downloadLog: "Télécharger le journal",
    logTitle: "Journal",
    noRejected: "Aucune question rejetée pour le moment.",
    replacementOf: "Remplacement {id}",
    logged: "Dans le journal",
    loadingLog: "Chargement du journal…",
    downloadedLog: "Journal des rejets téléchargé.",
    metrics: "Mesures",
    pending: "en attente",
    approved: "approuvée",
    rejected: "rejetée",
    approve: "Approuver",
    reject: "Rejeter",
    pendingBtn: "En attente",
    noQuestions: "Aucune question dans ce filtre.",
    addTopic: "Ajouter un thème",
    topicNote: "Ajoute à cette instance de Flow. Enregistrez-le dans le studio pour le conserver.",
    topics: "Thèmes",
    easyOnly: "facile seulement",
    awaiting: "En attente de revue",
    rejectedCard: "Rejetées",
    regenCard: "Journal des rejets",
    profilesCard: "Profils",
    roomsCard: "Salles ouvertes",
    refreshing: "Actualisation des banques, des profils et des salles…",
    countsNote: "Les comptes couvrent la banque de la semaine et le classement Dojo pour cette langue, plus les profils activés et les salles ouvertes.",
    glowTitle: "Glow",
    glowNote: "GMGbrand relie Flow à la salle de jeux — Fast Answer, SunFun et Last Call sur les cartes lumineuses.",
    openGlow: "Ouvrir Glow",
    openRooms: "Salles ouvertes",
    refreshRooms: "Actualiser les salles",
    roomsNote: "La même liste que Join TV. Une salle apparaît quand son lien TV est ouvert. Supprimer l'enlève pour tout le monde.",
    noRooms: "Aucune salle ouverte.",
    delete: "Supprimer",
    deletedRoom: "Salle {code} supprimée.",
    reviewQueue: "File de revue",
    refresh: "Actualiser",
    queueNote: "Questions en attente de revue ou déjà dans le journal des rejets — banque de la semaine et classement Dojo, langue {locale}.",
    waitingNone: "Aucune question n'attend une revue.",
    banksMissing: "Les banques de la semaine et du classement ne se sont pas chargées.",
    rejection: "Rejet",
    noRejectedQs: "Aucune question rejetée.",
    inLog: "Dans le journal des rejets",
    replacedBy: "Remplacement : {id}",
    noneLogged: "Aucune question dans le journal des rejets.",
    profiles: "Profils",
    downloadMail: "Télécharger la liste de diffusion",
    mailLine: "{n} activés · {n} e-mails. Le CSV contient chaque e-mail de cette liste.",
    mailOne: "{n} activé · {n} e-mail. Le CSV contient chaque e-mail de cette liste.",
    name: "Nom",
    email: "E-mail",
    activated: "Activé",
    status: "Statut",
    active: "Actif",
    noProfiles: "Aucun profil activé. Ils apparaissent quand un joueur touche Entrer le profil.",
    loadingQueue: "Chargement des questions, des profils et des salles…",
    mailDownloaded: "Liste de diffusion téléchargée.",
    bankReview: "Revue de la banque",
    noneWeek: "Rien cette semaine.",
    louisBlurb: "Garde Q&R · 13–16 ans. Psychologie de l'enfant et comportement : du plaisir, de la joie, et une forme qui ne menace pas.",
    louisCount: "{shaped} structurées · {held} retenues. Les notes peuvent aller à {mail}.",
    comedyBlurb: "Bot comédie Q&R · semaine {week}. Les nouvelles questions drôles, puis les mieux notées.",
    viralWeek: "Viral cette semaine",
    highest: "Les mieux notées",
    activatedProfiles: "Profils activés",
    profilesNote: "Les joueurs qui touchent Entrer le profil sont activés ici. La liste de diffusion contient chaque e-mail.",
    analytics: "Mesures",
    lastPublish: "Dernière publication",
    notYet: "pas encore",
    publishWeek: "Publier la semaine",
    localeSet: "Langue {locale}",
    topicAdded: "Thème ajouté (pour cette session).",
    durable: "Chemin durable : handoff, puis git push. Chaque langue a ses archives dans banks/archive.",
    tier_all: "tous",
    tier_easy: "facile",
    tier_hard: "difficile",
    tier_difficult: "ardu",
    tier_extreme: "extrême",
    tier_finale: "finale",
  },
  "fr-CA": {
    private: "Privé",
    loginSub: "Console Fast Answer, en français du Québec. Le mot de passe reste sur le serveur.",
    locked: "Session barrée — entrez le mot de passe encore une fois.",
    password: "Mot de passe",
    enter: "Entrer",
    backGame: "Retour au jeu",
    weekLine: "Semaine {week} · langue {locale} · revue, mesures, profils, salles.",
    play: "Jouer",
    logout: "Fermer la session",
    localeGroup: "Langue",
    tab_console: "Console",
    tab_metrics: "Mesures",
    tab_queue: "File",
    tab_profiles: "Profils",
    tab_rooms: "Salles",
    tab_bank: "Banque",
    tab_archive: "Archives",
    tab_topic: "Sujets",
    tab_reject: "Journal des rejets",
    loadingArchive: "Chargement des archives…",
    backArchives: "← Archives",
    backMonths: "← Tous les mois",
    placementTitle: "Classement",
    placementNote: "Banque de classement du Dojo. Remplacez une question ici. L'ancienne s'en va dans le journal des rejets.",
    monthlyTitle: "Archives du mois",
    monthlyNote: "Semaines publiées pour cette langue. Remplacer échange la question et l'envoie au journal des rejets.",
    questions: "questions",
    weekOne: "semaine",
    weekMany: "semaines",
    updated: "mise à jour",
    noWeeks: "Aucune semaine dans les archives ce mois-ci.",
    noPlacement: "Aucun classement n'est inclus.",
    emptyArchive: "Les archives sont vides. Publiez une semaine pour les remplir.",
    placementTag: "classement",
    filterPh: "Filtrer le sujet ou la question…",
    noFilter: "Aucune question dans ce filtre.",
    potential: "Remplacement possible",
    potentialShort: "Possible",
    readyShort: "Prêt",
    readyCount: "prêtes",
    replace: "Remplacer",
    noReplacement: "Pas de remplacement possible pour le moment.",
    replacedLogged: "{id} est remplacée. Cette question est dans le journal des rejets.",
    countsLine: "{counts} · {n} questions",
    rejectLogTitle: "Journal des rejets",
    rejectLogNote: "Une question remplacée aboutit ici. Les archives ne rejettent plus et ne régénèrent plus.",
    refreshLog: "Actualiser le journal",
    downloadLog: "Télécharger le journal",
    logTitle: "Journal",
    noRejected: "Aucune question rejetée pour le moment.",
    replacementOf: "Remplacement {id}",
    logged: "Dans le journal",
    loadingLog: "Chargement du journal…",
    downloadedLog: "Journal des rejets téléchargé.",
    metrics: "Mesures",
    pending: "en attente",
    approved: "approuvée",
    rejected: "rejetée",
    approve: "Approuver",
    reject: "Rejeter",
    pendingBtn: "En attente",
    noQuestions: "Aucune question dans ce filtre.",
    addTopic: "Ajouter un sujet",
    topicNote: "Ajoute à cette instance de Flow. Enregistrez-le dans le studio pour le garder.",
    topics: "Sujets",
    easyOnly: "facile seulement",
    awaiting: "En attente de revue",
    rejectedCard: "Rejetées",
    regenCard: "Journal des rejets",
    profilesCard: "Profils",
    roomsCard: "Salles ouvertes",
    refreshing: "Actualisation des banques, des profils et des salles…",
    countsNote: "Les comptes couvrent la banque de la semaine et le classement Dojo pour cette langue, plus les profils activés et les salles ouvertes.",
    glowTitle: "Glow",
    glowNote: "GMGbrand relie Flow à la salle de jeux — Fast Answer, SunFun et Last Call sur les cartes lumineuses.",
    openGlow: "Ouvrir Glow",
    openRooms: "Salles ouvertes",
    refreshRooms: "Actualiser les salles",
    roomsNote: "La même liste que Join TV. Une salle apparaît quand son lien TV est ouvert. Supprimer l'enlève pour tout le monde.",
    noRooms: "Aucune salle ouverte.",
    delete: "Supprimer",
    deletedRoom: "Salle {code} supprimée.",
    reviewQueue: "File de revue",
    refresh: "Actualiser",
    queueNote: "Questions en attente de revue ou déjà dans le journal des rejets — banque de la semaine et classement Dojo, langue {locale}.",
    waitingNone: "Aucune question n'attend une revue.",
    banksMissing: "Les banques de la semaine et du classement ne se sont pas chargées.",
    rejection: "Rejet",
    noRejectedQs: "Aucune question rejetée.",
    inLog: "Dans le journal des rejets",
    replacedBy: "Remplacement : {id}",
    noneLogged: "Aucune question dans le journal des rejets.",
    profiles: "Profils",
    downloadMail: "Télécharger la liste d'envoi",
    mailLine: "{n} activés · {n} courriels. Le CSV contient chaque courriel de cette liste.",
    mailOne: "{n} activé · {n} courriel. Le CSV contient chaque courriel de cette liste.",
    name: "Nom",
    email: "Courriel",
    activated: "Activé",
    status: "Statut",
    active: "Actif",
    noProfiles: "Aucun profil activé. Ils apparaissent quand un joueur touche Entrer le profil.",
    loadingQueue: "Chargement des questions, des profils et des salles…",
    mailDownloaded: "Liste d'envoi téléchargée.",
    bankReview: "Revue de la banque",
    noneWeek: "Rien cette semaine.",
    louisBlurb: "Garde Q&R · 13–16 ans. Psychologie de l'enfant et comportement : du plaisir, de la joie, et une forme qui ne menace pas.",
    louisCount: "{shaped} structurées · {held} retenues. Les notes peuvent aller à {mail}.",
    comedyBlurb: "Bot comédie Q&R · semaine {week}. Les nouvelles questions drôles, puis les mieux notées.",
    viralWeek: "Viral cette semaine",
    highest: "Les mieux notées",
    activatedProfiles: "Profils activés",
    profilesNote: "Les joueurs qui touchent Entrer le profil sont activés ici. La liste d'envoi contient chaque courriel.",
    louisBlurb: "Garde des questions · 13 à 16 ans. Psychologie de l'enfant et comportement : du plaisir, de la joie, et rien qui fait peur.",
    comedyBlurb: "Bot d'humour · semaine {week}. Les nouvelles questions drôles, puis les mieux notées.",
    analytics: "Mesures",
    lastPublish: "Dernière publication",
    notYet: "pas encore",
    publishWeek: "Publier la semaine",
    localeSet: "Langue {locale}",
    topicAdded: "Sujet ajouté (pour cette session).",
    durable: "Chemin durable : handoff, puis git push. Chaque langue a ses archives dans banks/archive.",
    tier_all: "tous",
    tier_easy: "facile",
    tier_hard: "difficile",
    tier_difficult: "ardu",
    tier_extreme: "extrême",
    tier_finale: "finale",
  },
  de: {
    private: "Privat",
    loginSub: "Fast-Answer-Konsole. Das Passwort bleibt auf dem Server.",
    locked: "Sitzung gesperrt — Passwort erneut eingeben.",
    password: "Passwort",
    enter: "Eintreten",
    backGame: "Zurück zum Spiel",
    weekLine: "Woche {week} · Sprache {locale} · Prüfung, Kennzahlen, Profile, Räume.",
    play: "Spielen",
    logout: "Abmelden",
    localeGroup: "Sprache",
    tab_console: "Konsole",
    tab_metrics: "Kennzahlen",
    tab_queue: "Warteschlange",
    tab_profiles: "Profile",
    tab_rooms: "Räume",
    tab_bank: "Bank",
    tab_archive: "Archiv",
    tab_topic: "Themen",
    tab_reject: "Ablehnungsprotokoll",
    loadingArchive: "Archiv wird geladen…",
    backArchives: "← Archiv",
    backMonths: "← Alle Monate",
    placementTitle: "Einstufung",
    placementNote: "Dojo-Einstufungsbank. Ersetzen Sie eine Frage hier. Die alte steht danach im Ablehnungsprotokoll.",
    monthlyTitle: "Monatsarchiv",
    monthlyNote: "Veröffentlichte Wochen dieser Sprache. Ersetzen tauscht die Frage und schreibt sie ins Ablehnungsprotokoll.",
    questions: "Fragen",
    weekOne: "Woche",
    weekMany: "Wochen",
    updated: "aktualisiert",
    noWeeks: "In diesem Monat ist keine Woche archiviert.",
    noPlacement: "Kein Einstufungspaket enthalten.",
    emptyArchive: "Archiv leer — veröffentlichen Sie eine Woche, um es zu füllen.",
    placementTag: "Einstufung",
    filterPh: "Thema oder Frage filtern…",
    noFilter: "Keine Fragen in diesem Filter.",
    potential: "Möglicher Ersatz",
    potentialShort: "Ersatz",
    readyShort: "Bereit",
    readyCount: "bereit",
    replace: "Ersetzen",
    noReplacement: "Noch kein möglicher Ersatz bereit.",
    replacedLogged: "{id} ersetzt. Diese Frage steht im Ablehnungsprotokoll.",
    countsLine: "{counts} · {n} Fragen",
    rejectLogTitle: "Ablehnungsprotokoll",
    rejectLogNote: "Eine ersetzte Frage landet hier. Das Archiv lehnt nicht mehr ab und erzeugt nicht neu.",
    refreshLog: "Protokoll aktualisieren",
    downloadLog: "Protokoll herunterladen",
    logTitle: "Protokoll",
    noRejected: "Noch keine abgelehnten Fragen.",
    replacementOf: "Ersatz {id}",
    logged: "Im Protokoll",
    loadingLog: "Protokoll wird geladen…",
    downloadedLog: "Ablehnungsprotokoll heruntergeladen.",
    metrics: "Kennzahlen",
    pending: "offen",
    approved: "freigegeben",
    rejected: "abgelehnt",
    approve: "Freigeben",
    reject: "Ablehnen",
    pendingBtn: "Offen",
    noQuestions: "Keine Fragen in diesem Filter.",
    addTopic: "Thema hinzufügen",
    topicNote: "Gilt für diese Flow-Instanz. Im Studio sichern, damit es bleibt.",
    topics: "Themen",
    easyOnly: "nur leicht",
    awaiting: "Wartet auf Prüfung",
    rejectedCard: "Abgelehnt",
    regenCard: "Ablehnungsprotokoll",
    profilesCard: "Profile",
    roomsCard: "Offene Räume",
    refreshing: "Banken, Profile und Räume werden aktualisiert…",
    countsNote: "Die Zahlen gelten für die Wochenbank und die Dojo-Einstufung dieser Sprache, plus aktivierte Profile und offene Räume.",
    glowTitle: "Glow",
    glowNote: "GMGbrand verbindet Flow mit dem Spieleraum — Fast Answer, SunFun und Last Call auf den leuchtenden Karten.",
    openGlow: "Glow öffnen",
    openRooms: "Offene Räume",
    refreshRooms: "Räume aktualisieren",
    roomsNote: "Dieselbe Liste wie Join TV. Ein Raum erscheint, wenn sein TV-Link offen ist. Löschen entfernt ihn für alle.",
    noRooms: "Keine offenen Räume.",
    delete: "Löschen",
    deletedRoom: "Raum {code} gelöscht.",
    reviewQueue: "Prüfwarteschlange",
    refresh: "Aktualisieren",
    queueNote: "Fragen, die auf Prüfung warten oder schon im Ablehnungsprotokoll stehen — Wochenbank und Dojo-Einstufung, Sprache {locale}.",
    waitingNone: "Keine Frage wartet auf Prüfung.",
    banksMissing: "Wochen- und Einstufungsbank wurden nicht geladen.",
    rejection: "Ablehnung",
    noRejectedQs: "Keine abgelehnten Fragen.",
    inLog: "Im Ablehnungsprotokoll",
    replacedBy: "Ersatz: {id}",
    noneLogged: "Keine Fragen im Ablehnungsprotokoll.",
    profiles: "Profile",
    downloadMail: "Verteiler herunterladen",
    mailLine: "{n} aktiviert · {n} E-Mails. Die CSV enthält jede E-Mail dieser Liste.",
    mailOne: "{n} aktiviert · {n} E-Mail. Die CSV enthält jede E-Mail dieser Liste.",
    name: "Name",
    email: "E-Mail",
    activated: "Aktiviert",
    status: "Status",
    active: "Aktiv",
    noProfiles: "Noch keine aktivierten Profile. Sie erscheinen, wenn ein Spieler Profil öffnen tippt.",
    loadingQueue: "Fragen, Profile und Räume werden geladen…",
    mailDownloaded: "Verteiler heruntergeladen.",
    localeSet: "Sprache {locale}",
    topicAdded: "Thema hinzugefügt (für diese Sitzung).",
    durable: "Dauerhafter Weg: Handoff, dann git push. Jede Sprache hat ein eigenes Archiv unter banks/archive.",
    bankReview: "Prüfung der Wochenbank",
    noneWeek: "Nichts in dieser Woche.",
    louisBlurb: "Q&A-Schutz · 13–16 Jahre. Kinderpsychologie und Verhalten: Spaß, Freude und eine Form ohne Drohung.",
    louisCount: "{shaped} geformt · {held} zurückgehalten. Notizen können an {mail}.",
    comedyBlurb: "Q&A-Comedy-Bot · Woche {week}. Neue lustige Fragen, dann die bestbewerteten.",
    viralWeek: "Viral diese Woche",
    highest: "Am höchsten bewertet",
    activatedProfiles: "Aktivierte Profile",
    profilesNote: "Spieler, die Profil öffnen tippen, werden hier aktiviert. Der Verteiler enthält jede E-Mail dieser Liste.",
    analytics: "Kennzahlen",
    lastPublish: "Letzte Veröffentlichung",
    notYet: "noch nicht",
    publishWeek: "Woche veröffentlichen",
    tier_all: "alle",
    tier_easy: "leicht",
    tier_hard: "schwer",
    tier_difficult: "anspruchsvoll",
    tier_extreme: "extrem",
    tier_finale: "Finale",
  },
};

export function t(locale, key, vars = {}) {
  const loc = normalizeFlowLocale(locale);
  const table = STRINGS[loc] || STRINGS.en;
  let text = table[key] || STRINGS.en[key] || key;
  for (const [name, value] of Object.entries(vars)) {
    text = text.replaceAll(`{${name}}`, String(value ?? ""));
  }
  return text;
}

export function flowLocaleLabel(locale) {
  const loc = normalizeFlowLocale(locale);
  if (loc === "fr-CA") return "QC";
  return loc.toUpperCase();
}
