/**
 * One creator for each generation pack. They write original questions.
 * Some jokes are easy or hard for general play. Colour questions ask
 * "What colour is…". Gen Alpha jokes stay on easy or hard.
 */
import { translateQuestion } from "./translators.js";

const WEEK = "2026-W39";

function q(row) {
  return { addedWeek: WEEK, sources: row.sources || [], ...row };
}

export const CREATORS = [
  {
    bot: "Creator Silent",
    generation: "silent-generation",
    questions: [
      q({
        id: "cq-e-silent-roar",
        tier: "easy",
        topic: "current-culture",
        generation: "silent-generation",
        correctIndex: 0,
        sources: [{ label: "Library of Congress — American history" }, { label: "Encyclopaedia Britannica — 1920s" }],
        text: {
          en: { categoryTitle: "Jazz Decade", prompt: "What nickname is given to the 1920s in the United States?", choices: ["The Roaring Twenties", "The Gilded Age", "The Depression Years", "The Space Age"], banterHint: "The bands were loud. The name stuck." },
          fr: { categoryTitle: "Décennie jazz", prompt: "Quel surnom donne-t-on aux années 1920 aux États-Unis ?", choices: ["Les Années folles", "L'Âge doré", "Les années de crise", "L'ère spatiale"], banterHint: "Les orchestres jouaient fort. Le surnom est resté." },
          "fr-CA": { categoryTitle: "Décennie jazz", prompt: "Les années 1920 aux États-Unis portent quel surnom ?", choices: ["Les années folles", "L'âge d'or", "Les années de la Crise", "L'ère de l'espace"], banterHint: "Les orchestres jouaient fort. Le surnom est resté." },
          de: { categoryTitle: "Jazzjahrzehnt", prompt: "Welchen Spitznamen tragen die 1920er-Jahre in den USA?", choices: ["Die wilden Zwanziger", "Das vergoldete Zeitalter", "Die Depressionsjahre", "Das Raumfahrtzeitalter"], banterHint: "Die Bands waren laut. Der Name blieb." },
        },
      }),
      q({
        id: "cq-e-silent-vote",
        tier: "easy",
        topic: "current-culture",
        generation: "silent-generation",
        correctIndex: 0,
        sources: [{ label: "National Archives — 19th Amendment" }, { label: "Encyclopaedia Britannica — women's suffrage" }],
        text: {
          en: { categoryTitle: "Ballot Box", prompt: "Which U.S. constitutional amendment, ratified in 1920, recognized women's right to vote?", choices: ["The 19th Amendment", "The 15th Amendment", "The 13th Amendment", "The 26th Amendment"], banterHint: "The line at the poll got longer, on purpose." },
          fr: { categoryTitle: "Urne", prompt: "Quel amendement de la Constitution américaine, ratifié en 1920, a reconnu le droit de vote des femmes ?", choices: ["Le 19e amendement", "Le 15e amendement", "Le 13e amendement", "Le 26e amendement"], banterHint: "La file devant l'urne s'est allongée, exprès." },
          "fr-CA": { categoryTitle: "Urne", prompt: "Quel amendement de la Constitution des États-Unis, ratifié en 1920, reconnaît le droit de vote des femmes ?", choices: ["Le 19e amendement", "Le 15e amendement", "Le 13e amendement", "Le 26e amendement"], banterHint: "La file devant le bureau de vote a allongé, pour de bon." },
          de: { categoryTitle: "Wahlurne", prompt: "Welche Ergänzung der US-Verfassung von 1920 erkennt das Wahlrecht der Frauen an?", choices: ["Der 19. Zusatzartikel", "Der 15. Zusatzartikel", "Der 13. Zusatzartikel", "Der 26. Zusatzartikel"], banterHint: "Die Schlange vor dem Wahllokal wurde absichtlich länger." },
        },
      }),
      q({
        id: "cq-h-silent-chamberlain",
        tier: "hard",
        topic: "current-culture",
        generation: "silent-generation",
        correctIndex: 0,
        sources: [{ label: "UK National Archives — 1939" }, { label: "Encyclopaedia Britannica — Neville Chamberlain" }],
        text: {
          en: { categoryTitle: "September 1939", prompt: "Who was Prime Minister of the United Kingdom when Britain declared war on Germany in 1939?", choices: ["Neville Chamberlain", "Winston Churchill", "Clement Attlee", "Stanley Baldwin"], banterHint: "Churchill took the chair the next year." },
          fr: { categoryTitle: "Septembre 1939", prompt: "Qui était Premier ministre du Royaume-Uni lorsque la Grande-Bretagne a déclaré la guerre à l'Allemagne en 1939 ?", choices: ["Neville Chamberlain", "Winston Churchill", "Clement Attlee", "Stanley Baldwin"], banterHint: "Churchill a pris le fauteuil l'année suivante." },
          "fr-CA": { categoryTitle: "Septembre 1939", prompt: "Qui était le premier ministre du Royaume-Uni quand la Grande-Bretagne a déclaré la guerre à l'Allemagne en 1939 ?", choices: ["Neville Chamberlain", "Winston Churchill", "Clement Attlee", "Stanley Baldwin"], banterHint: "Churchill a pris la place l'année d'après." },
          de: { categoryTitle: "September 1939", prompt: "Wer war Premierminister des Vereinigten Königreichs, als Großbritannien 1939 Deutschland den Krieg erklärte?", choices: ["Neville Chamberlain", "Winston Churchill", "Clement Attlee", "Stanley Baldwin"], banterHint: "Churchill übernahm den Stuhl im Jahr darauf." },
        },
      }),
      q({
        id: "cq-h-silent-assembly",
        tier: "hard",
        topic: "current-culture",
        generation: "silent-generation",
        correctIndex: 0,
        sources: [{ label: "United Nations — General Assembly history" }, { label: "Encyclopaedia Britannica — United Nations" }],
        text: {
          en: { categoryTitle: "First Session", prompt: "In which city did the United Nations hold its first General Assembly in 1946?", choices: ["London", "New York", "Geneva", "Paris"], banterHint: "New York became home a few years later." },
          fr: { categoryTitle: "Première session", prompt: "Dans quelle ville l'ONU a-t-elle tenu sa première Assemblée générale en 1946 ?", choices: ["Londres", "New York", "Genève", "Paris"], banterHint: "New York est devenu le siège quelques années plus tard." },
          "fr-CA": { categoryTitle: "Première session", prompt: "Dans quelle ville l'ONU a tenu sa première Assemblée générale en 1946 ?", choices: ["Londres", "New York", "Genève", "Paris"], banterHint: "New York est devenu le siège quelques années plus tard." },
          de: { categoryTitle: "Erste Sitzung", prompt: "In welcher Stadt hielt die UNO 1946 ihre erste Generalversammlung ab?", choices: ["London", "New York", "Genf", "Paris"], banterHint: "New York wurde ein paar Jahre später der Sitz." },
        },
      }),
      q({
        id: "cq-e-silent-radio",
        tier: "easy",
        topic: "current-culture",
        generation: "silent-generation",
        funny: true,
        technique: "wordplay",
        structure: "joke",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "By the Window", prompt: "Why did the radio sit near the window?", choices: ["It wanted to catch a wave", "It hid from the news", "It lost the dial", "It preferred silence"], banterHint: "The song still came through." },
          fr: { categoryTitle: "Près de la fenêtre", prompt: "Pourquoi la radio s'est-elle assise près de la fenêtre ?", choices: ["Elle voulait capter une onde", "Elle se cachait des nouvelles", "Elle a perdu le cadran", "Elle préférait le silence"], banterHint: "La chanson passait quand même." },
          "fr-CA": { categoryTitle: "Près de la fenêtre", prompt: "Pourquoi la radio s'est assise près de la fenêtre ?", choices: ["Elle voulait capter une onde", "Elle se cachait des nouvelles", "Elle a perdu le cadran", "Elle préférait le silence"], banterHint: "La chanson passait quand même." },
          de: { categoryTitle: "Am Fenster", prompt: "Warum saß das Radio am Fenster?", choices: ["Es wollte eine Welle fangen", "Es versteckte sich vor den Nachrichten", "Es verlor die Skala", "Es wollte Stille"], banterHint: "Das Lied kam trotzdem durch." },
        },
      }),
      q({
        id: "cq-e-silent-liberty",
        tier: "easy",
        topic: "current-culture",
        generation: "silent-generation",
        structure: "colour",
        fromStructure: "colour",
        humorous: true,
        funny: true,
        injection: "dialogue",
        technique: "dialogue",
        correctIndex: 0,
        jokeWrongs: {
          2: {
            en: "Gold, if the torch is telling the story",
            fr: "Or, si le flambeau raconte l'histoire",
            "fr-CA": "Or, si le flambeau raconte l'histoire",
            de: "Gold, wenn die Fackel die Geschichte erzählt",
          },
          3: {
            en: "White, still shy from the crossing",
            fr: "Blanc, encore timide après la traversée",
            "fr-CA": "Blanc, encore timide après la traversée",
            de: "Weiß, noch schüchtern von der Überfahrt",
          },
        },
        sources: [{ label: "National Park Service — Statue of Liberty" }, { label: "Encyclopaedia Britannica — Statue of Liberty" }],
        text: {
          en: { categoryTitle: "Copper Coat", prompt: "What colour is the Statue of Liberty today?", choices: ["Green", "Grey", "Gold", "White"], banterHint: "The copper coat changed after years of weather." },
          fr: { categoryTitle: "Manteau de cuivre", prompt: "De quelle couleur est la Statue de la Liberté aujourd'hui ?", choices: ["Vert", "Gris", "Or", "Blanc"], banterHint: "Le cuivre a changé après des années de temps." },
          "fr-CA": { categoryTitle: "Manteau de cuivre", prompt: "C'est quoi la couleur de la Statue de la Liberté aujourd'hui ?", choices: ["Vert", "Gris", "Or", "Blanc"], banterHint: "Le cuivre a changé après des années de temps." },
          de: { categoryTitle: "Kupfermantel", prompt: "Welche Farbe hat die Freiheitsstatue heute?", choices: ["Grün", "Grau", "Gold", "Weiß"], banterHint: "Das Kupfer hat sich nach Jahren Wetter verändert." },
        },
      }),
      q({
        id: "cq-h-silent-empire",
        tier: "hard",
        topic: "current-culture",
        generation: "silent-generation",
        structure: "when",
        correctIndex: 0,
        sources: [{ label: "Encyclopaedia Britannica — Empire State Building" }, { label: "New York City Landmarks — Empire State Building" }],
        text: {
          en: { categoryTitle: "Skyline", prompt: "When was the Empire State Building completed?", choices: ["1931", "1925", "1941", "1950"], banterHint: "The spire was up before the decade turned." },
          fr: { categoryTitle: "Horizon", prompt: "Quand l'Empire State Building a-t-il été achevé ?", choices: ["1931", "1925", "1941", "1950"], banterHint: "La flèche était en place avant la fin de la décennie." },
          "fr-CA": { categoryTitle: "Horizon", prompt: "L'Empire State Building a été achevé quand ?", choices: ["1931", "1925", "1941", "1950"], banterHint: "La flèche était en place avant la fin de la décennie." },
          de: { categoryTitle: "Skyline", prompt: "Wann wurde das Empire State Building fertig?", choices: ["1931", "1925", "1941", "1950"], banterHint: "Die Spitze stand, bevor das Jahrzehnt um war." },
        },
      }),
      q({
        id: "cq-e-silent-taxi",
        tier: "easy",
        topic: "current-culture",
        generation: "silent-generation",
        structure: "colour",
        fromStructure: "colour",
        humorous: true,
        funny: true,
        injection: "straight-man",
        technique: "straight-man",
        correctIndex: 0,
        jokeWrongs: {
          2: {
            en: "Black, dressed for a very serious errand",
            fr: "Noir, habillé pour une course très sérieuse",
            "fr-CA": "Noir, habillé pour une course très sérieuse",
            de: "Schwarz, angezogen für einen sehr ernsten Auftrag",
          },
          3: {
            en: "White, trying out for the ice cream truck",
            fr: "Blanc, en audition pour le camion de crème glacée",
            "fr-CA": "Blanc, à l'audition du camion de crème glacée",
            de: "Weiß, beim Vorsprechen für den Eiswagen",
          },
        },
        sources: [{ label: "NYC Taxi and Limousine Commission" }, { label: "Encyclopaedia Britannica — taxicab" }],
        text: {
          en: { categoryTitle: "Medallion", prompt: "What colour is a classic New York City taxi?", choices: ["Yellow", "Green", "Black", "White"], banterHint: "The wild guess can wait. The cab is the bright one." },
          fr: { categoryTitle: "Médaille", prompt: "De quelle couleur est un taxi classique de New York ?", choices: ["Jaune", "Vert", "Noir", "Blanc"], banterHint: "La devinette folle peut attendre. Le taxi est le vif." },
          "fr-CA": { categoryTitle: "Médaille", prompt: "C'est quoi la couleur d'un taxi classique de New York ?", choices: ["Jaune", "Vert", "Noir", "Blanc"], banterHint: "La devinette folle peut attendre. Le taxi est le vif." },
          de: { categoryTitle: "Medaillon", prompt: "Welche Farbe hat ein klassisches New Yorker Taxi?", choices: ["Gelb", "Grün", "Schwarz", "Weiß"], banterHint: "Das wilde Raten kann warten. Das Taxi ist das helle." },
        },
      }),
      q({
        id: "cq-e-silent-adenauer",
        tier: "easy",
        topic: "current-culture",
        generation: "silent-generation",
        correctIndex: 0,
        sources: [{ label: "German Federal Archives — Konrad Adenauer" }, { label: "Encyclopaedia Britannica — Konrad Adenauer" }],
        text: {
          en: { categoryTitle: "First Chancellor", prompt: "Who was the first Chancellor of West Germany?", choices: ["Konrad Adenauer", "Willy Brandt", "Helmut Kohl", "Helmut Schmidt"], banterHint: "He took the chair in 1949 and kept it for a long stretch." },
          fr: { categoryTitle: "Premier chancelier", prompt: "Qui a été le premier chancelier de l'Allemagne de l'Ouest ?", choices: ["Konrad Adenauer", "Willy Brandt", "Helmut Kohl", "Helmut Schmidt"], banterHint: "Il a pris le fauteuil en 1949 et l'a gardé longtemps." },
          "fr-CA": { categoryTitle: "Premier chancelier", prompt: "Qui a été le premier chancelier de l'Allemagne de l'Ouest ?", choices: ["Konrad Adenauer", "Willy Brandt", "Helmut Kohl", "Helmut Schmidt"], banterHint: "Il a pris le fauteuil en 1949 et l'a gardé longtemps." },
          de: { categoryTitle: "Erster Kanzler", prompt: "Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?", choices: ["Konrad Adenauer", "Willy Brandt", "Helmut Kohl", "Helmut Schmidt"], banterHint: "Er übernahm den Stuhl 1949 und behielt ihn lange." },
        },
      }),
      q({
        id: "cq-h-silent-marshall",
        tier: "hard",
        topic: "current-culture",
        generation: "silent-generation",
        correctIndex: 0,
        sources: [{ label: "US National Archives — Marshall Plan" }, { label: "Encyclopaedia Britannica — Marshall Plan" }],
        text: {
          en: { categoryTitle: "Recovery Act", prompt: "In which year did the Marshall Plan become law in the United States?", choices: ["1948", "1945", "1951", "1953"], banterHint: "The war was already over. The rebuild had a start date." },
          fr: { categoryTitle: "Loi de relève", prompt: "En quelle année le plan Marshall est-il devenu une loi aux États-Unis ?", choices: ["1948", "1945", "1951", "1953"], banterHint: "La guerre était finie. La reconstruction a une date de départ." },
          "fr-CA": { categoryTitle: "Loi de relève", prompt: "En quelle année le plan Marshall est devenu une loi aux États-Unis ?", choices: ["1948", "1945", "1951", "1953"], banterHint: "La guerre était finie. La reconstruction a une date de départ." },
          de: { categoryTitle: "Aufbaugesetz", prompt: "In welchem Jahr wurde der Marshallplan in den USA Gesetz?", choices: ["1948", "1945", "1951", "1953"], banterHint: "Der Krieg war vorbei. Der Aufbau hat ein Startdatum." },
        },
      }),
    ],
  },
  {
    bot: "Creator Boomer",
    generation: "baby-boomer",
    questions: [
      q({
        id: "cq-e-boomer-gaye",
        tier: "easy",
        topic: "music",
        generation: "baby-boomer",
        correctIndex: 1,
        sources: [{ label: "Motown / album notes — What's Going On" }, { label: "Encyclopaedia Britannica — Marvin Gaye" }],
        text: {
          en: { categoryTitle: "Soul Hour", prompt: "Who released the album What's Going On in 1971?", choices: ["Stevie Wonder", "Marvin Gaye", "Otis Redding", "Sam Cooke"], banterHint: "The questions on that record still stand." },
          fr: { categoryTitle: "Heure soul", prompt: "Qui a sorti l'album What's Going On en 1971 ?", choices: ["Stevie Wonder", "Marvin Gaye", "Otis Redding", "Sam Cooke"], banterHint: "Les questions de ce disque tiennent encore." },
          "fr-CA": { categoryTitle: "Heure soul", prompt: "Qui a lancé l'album What's Going On en 1971 ?", choices: ["Stevie Wonder", "Marvin Gaye", "Otis Redding", "Sam Cooke"], banterHint: "Les questions de ce disque tiennent encore." },
          de: { categoryTitle: "Soul-Stunde", prompt: "Wer veröffentlichte 1971 das Album What's Going On?", choices: ["Stevie Wonder", "Marvin Gaye", "Otis Redding", "Sam Cooke"], banterHint: "Die Fragen auf der Platte gelten noch." },
        },
      }),
      q({
        id: "cq-e-boomer-skylab",
        tier: "easy",
        topic: "current-culture",
        generation: "baby-boomer",
        correctIndex: 2,
        sources: [{ label: "NASA — Skylab" }, { label: "Encyclopaedia Britannica — space stations" }],
        text: {
          en: { categoryTitle: "Workshop in Orbit", prompt: "What was the name of NASA's first space station, launched in 1973?", choices: ["Mir", "Salyut", "Skylab", "Freedom"], banterHint: "A workshop with a very long commute." },
          fr: { categoryTitle: "Atelier en orbite", prompt: "Comment s'appelait la première station spatiale de la NASA, lancée en 1973 ?", choices: ["Mir", "Saliout", "Skylab", "Freedom"], banterHint: "Un atelier avec un très long trajet." },
          "fr-CA": { categoryTitle: "Atelier en orbite", prompt: "Quel était le nom de la première station spatiale de la NASA, lancée en 1973 ?", choices: ["Mir", "Saliout", "Skylab", "Freedom"], banterHint: "Un atelier avec un très long trajet." },
          de: { categoryTitle: "Werkstatt im Orbit", prompt: "Wie hieß die erste Raumstation der NASA, gestartet 1973?", choices: ["Mir", "Saljut", "Skylab", "Freedom"], banterHint: "Eine Werkstatt mit sehr langem Arbeitsweg." },
        },
      }),
      q({
        id: "cq-h-boomer-sesame",
        tier: "hard",
        topic: "film-tv",
        generation: "baby-boomer",
        correctIndex: 0,
        sources: [{ label: "Sesame Workshop — history" }, { label: "Library of Congress — television history" }],
        text: {
          en: { categoryTitle: "Street Premiere", prompt: "In which year did Sesame Street first air in the United States?", choices: ["1969", "1965", "1974", "1979"], banterHint: "The street opened near the end of the sixties." },
          fr: { categoryTitle: "Première dans la rue", prompt: "En quelle année Sesame Street a-t-il été diffusé pour la première fois aux États-Unis ?", choices: ["1969", "1965", "1974", "1979"], banterHint: "La rue a ouvert vers la fin des années soixante." },
          "fr-CA": { categoryTitle: "Première dans la rue", prompt: "En quelle année Sesame Street a été diffusé pour la première fois aux États-Unis ?", choices: ["1969", "1965", "1974", "1979"], banterHint: "La rue a ouvert vers la fin des années soixante." },
          de: { categoryTitle: "Straßenpremiere", prompt: "In welchem Jahr lief Sesame Street zum ersten Mal in den USA?", choices: ["1969", "1965", "1974", "1979"], banterHint: "Die Straße öffnete gegen Ende der Sechziger." },
        },
      }),
      q({
        id: "cq-h-boomer-earthday",
        tier: "hard",
        topic: "current-culture",
        generation: "baby-boomer",
        correctIndex: 1,
        sources: [{ label: "Earth Day Network — history" }, { label: "U.S. EPA — Earth Day" }],
        text: {
          en: { categoryTitle: "First Green Day", prompt: "In which year was the first Earth Day held?", choices: ["1962", "1970", "1977", "1984"], banterHint: "The planet got a date on the calendar." },
          fr: { categoryTitle: "Premier jour vert", prompt: "En quelle année a eu lieu le premier Jour de la Terre ?", choices: ["1962", "1970", "1977", "1984"], banterHint: "La planète a eu une date au calendrier." },
          "fr-CA": { categoryTitle: "Premier jour vert", prompt: "En quelle année a eu lieu le premier Jour de la Terre ?", choices: ["1962", "1970", "1977", "1984"], banterHint: "La planète a eu une date au calendrier." },
          de: { categoryTitle: "Erster grüner Tag", prompt: "In welchem Jahr fand der erste Earth Day statt?", choices: ["1962", "1970", "1977", "1984"], banterHint: "Der Planet bekam ein Datum im Kalender." },
        },
      }),
      q({
        id: "cq-h-boomer-record",
        tier: "hard",
        topic: "current-culture",
        generation: "baby-boomer",
        funny: true,
        technique: "callback",
        structure: "joke",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "Spin Again", prompt: "Why did the record stay friends with the player?", choices: ["It kept coming back around", "It hid in the sleeve", "It skipped the chorus", "It lost the label"], banterHint: "The next song still got a turn." },
          fr: { categoryTitle: "Encore un tour", prompt: "Pourquoi le disque est-il resté ami avec le tourne-disque ?", choices: ["Il revenait toujours", "Il se cachait dans la pochette", "Il sautait le refrain", "Il a perdu l'étiquette"], banterHint: "La chanson suivante a eu son tour." },
          "fr-CA": { categoryTitle: "Encore un tour", prompt: "Pourquoi le disque est resté ami avec le tourne-disque ?", choices: ["Il revenait toujours", "Il se cachait dans la pochette", "Il sautait le refrain", "Il a perdu l'étiquette"], banterHint: "La chanson suivante a eu son tour." },
          de: { categoryTitle: "Noch eine Runde", prompt: "Warum blieb die Schallplatte mit dem Spieler befreundet?", choices: ["Sie kam immer wieder herum", "Sie versteckte sich in der Hülle", "Sie übersprang den Refrain", "Sie verlor das Etikett"], banterHint: "Das nächste Lied kam trotzdem dran." },
        },
      }),
      q({
        id: "cq-e-boomer-submarine",
        tier: "easy",
        topic: "current-culture",
        generation: "baby-boomer",
        structure: "colour",
        correctIndex: 0,
        sources: [{ label: "Encyclopaedia Britannica — the Beatles" }, { label: "Library of Congress — Yellow Submarine" }],
        text: {
          en: { categoryTitle: "Under the Sea", prompt: "What colour is the submarine in the Beatles song?", choices: ["Yellow", "Blue", "Red", "Green"], banterHint: "The title gives the paint job away." },
          fr: { categoryTitle: "Sous la mer", prompt: "De quelle couleur est le sous-marin dans la chanson des Beatles ?", choices: ["Jaune", "Bleu", "Rouge", "Vert"], banterHint: "Le titre donne déjà la peinture." },
          "fr-CA": { categoryTitle: "Sous la mer", prompt: "C'est quoi la couleur du sous-marin dans la chanson des Beatles ?", choices: ["Jaune", "Bleu", "Rouge", "Vert"], banterHint: "Le titre donne déjà la peinture." },
          de: { categoryTitle: "Unter dem Meer", prompt: "Welche Farbe hat das U-Boot im Beatles-Lied?", choices: ["Gelb", "Blau", "Rot", "Grün"], banterHint: "Der Titel verrät schon die Farbe." },
        },
      }),
      q({
        id: "cq-h-boomer-gate",
        tier: "hard",
        topic: "current-culture",
        generation: "baby-boomer",
        structure: "colour",
        correctIndex: 0,
        sources: [{ label: "Golden Gate Bridge Highway and Transportation District" }, { label: "Encyclopaedia Britannica — Golden Gate Bridge" }],
        text: {
          en: { categoryTitle: "Span", prompt: "What colour is the Golden Gate Bridge?", choices: ["International Orange", "Gold", "Red", "Blue"], banterHint: "The name sounds like gold. The paint is the other one." },
          fr: { categoryTitle: "Travée", prompt: "De quelle couleur est le pont du Golden Gate ?", choices: ["Orange international", "Or", "Rouge", "Bleu"], banterHint: "Le nom sonne comme l'or. La peinture est l'autre." },
          "fr-CA": { categoryTitle: "Travée", prompt: "C'est quoi la couleur du pont du Golden Gate ?", choices: ["Orange international", "Or", "Rouge", "Bleu"], banterHint: "Le nom sonne comme l'or. La peinture est l'autre." },
          de: { categoryTitle: "Spannweite", prompt: "Welche Farbe hat die Golden Gate Bridge?", choices: ["International Orange", "Gold", "Rot", "Blau"], banterHint: "Der Name klingt nach Gold. Die Farbe ist die andere." },
        },
      }),
      q({
        id: "cq-e-boomer-woodstock",
        tier: "easy",
        topic: "current-culture",
        generation: "baby-boomer",
        structure: "when",
        fromStructure: "when",
        humorous: true,
        funny: true,
        injection: "rule-of-three",
        technique: "rule-of-three",
        correctIndex: 0,
        jokeWrongs: {
          2: {
            en: "July 4, when the fireworks thought they were the band",
            fr: "4 juillet, quand les feux d'artifice se prenaient pour le groupe",
            "fr-CA": "4 juillet, quand les feux d'artifice se prenaient pour le groupe",
            de: "4. Juli, als das Feuerwerk dachte, es sei die Band",
          },
          3: {
            en: "June 1, a month early and already muddy",
            fr: "1 juin, un mois trop tôt et déjà boueux",
            "fr-CA": "1er juin, un mois trop tôt et déjà boueux",
            de: "1. Juni, einen Monat zu früh und schon matschig",
          },
        },
        sources: [{ label: "Bethel Woods Center for the Arts — Woodstock" }, { label: "Encyclopaedia Britannica — Woodstock" }],
        text: {
          en: { categoryTitle: "The Field", prompt: "When did the Woodstock festival begin?", choices: ["August 15, 1969", "August 15, 1967", "July 4, 1970", "June 1, 1968"], banterHint: "Two wrong dates, then the Friday it opened." },
          fr: { categoryTitle: "Le champ", prompt: "Quand le festival de Woodstock a-t-il commencé ?", choices: ["15 août 1969", "15 août 1967", "4 juillet 1970", "1 juin 1968"], banterHint: "Deux mauvaises dates, puis le vendredi d'ouverture." },
          "fr-CA": { categoryTitle: "Le champ", prompt: "Le festival de Woodstock a commencé quand ?", choices: ["15 août 1969", "15 août 1967", "4 juillet 1970", "1 juin 1968"], banterHint: "Deux mauvaises dates, puis le vendredi d'ouverture." },
          de: { categoryTitle: "Das Feld", prompt: "Wann begann das Woodstock-Festival?", choices: ["15. August 1969", "15. August 1967", "4. Juli 1970", "1. Juni 1968"], banterHint: "Zwei falsche Daten, dann der Freitag der Eröffnung." },
        },
      }),
      q({
        id: "cq-e-boomer-parks",
        tier: "easy",
        topic: "current-culture",
        generation: "baby-boomer",
        correctIndex: 0,
        sources: [{ label: "US National Archives — Rosa Parks" }, { label: "Encyclopaedia Britannica — Montgomery bus boycott" }],
        text: {
          en: { categoryTitle: "December 1", prompt: "Whose arrest in Montgomery on December 1, 1955, started the bus boycott?", choices: ["Rosa Parks", "Claudette Colvin", "Ella Baker", "Dorothy Height"], banterHint: "The seat stayed taken. The boycott followed." },
          fr: { categoryTitle: "1er décembre", prompt: "L'arrestation de qui, à Montgomery le 1er décembre 1955, a lancé le boycott des bus ?", choices: ["Rosa Parks", "Claudette Colvin", "Ella Baker", "Dorothy Height"], banterHint: "La place est restée prise. Le boycott a suivi." },
          "fr-CA": { categoryTitle: "1er décembre", prompt: "L'arrestation de qui, à Montgomery le 1er décembre 1955, a lancé le boycott des autobus ?", choices: ["Rosa Parks", "Claudette Colvin", "Ella Baker", "Dorothy Height"], banterHint: "La place est restée prise. Le boycott a suivi." },
          de: { categoryTitle: "1. Dezember", prompt: "Wessen Festnahme in Montgomery am 1. Dezember 1955 löste den Busboykott aus?", choices: ["Rosa Parks", "Claudette Colvin", "Ella Baker", "Dorothy Height"], banterHint: "Der Platz blieb besetzt. Der Boykott folgte." },
        },
      }),
      q({
        id: "cq-h-boomer-gold",
        tier: "hard",
        topic: "current-culture",
        generation: "baby-boomer",
        correctIndex: 0,
        sources: [{ label: "IUPAC — gold" }, { label: "Encyclopaedia Britannica — gold" }],
        text: {
          en: { categoryTitle: "Element", prompt: "What is the chemical symbol for gold?", choices: ["Au", "Ag", "Fe", "Cu"], banterHint: "Silver is the neighbour on the chart." },
          fr: { categoryTitle: "Élément", prompt: "Quel est le symbole chimique de l'or ?", choices: ["Au", "Ag", "Fe", "Cu"], banterHint: "L'argent est le voisin sur le tableau." },
          "fr-CA": { categoryTitle: "Élément", prompt: "C'est quoi le symbole chimique de l'or ?", choices: ["Au", "Ag", "Fe", "Cu"], banterHint: "L'argent est le voisin sur le tableau." },
          de: { categoryTitle: "Element", prompt: "Welches chemische Zeichen steht für Gold?", choices: ["Au", "Ag", "Fe", "Cu"], banterHint: "Silber ist der Nachbar in der Tabelle." },
        },
      }),
    ],
  },
  {
    bot: "Creator Gen X",
    generation: "gen-x",
    questions: [
      q({
        id: "cq-e-genx-gameboy",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-x",
        correctIndex: 0,
        sources: [{ label: "Nintendo — Game Boy history" }, { label: "Encyclopaedia Britannica — video game consoles" }],
        text: {
          en: { categoryTitle: "Pocket Screen", prompt: "Which handheld console did Nintendo release in 1989?", choices: ["Game Boy", "Game Gear", "Lynx", "PSP"], banterHint: "Tetris rode along in a lot of pockets." },
          fr: { categoryTitle: "Écran de poche", prompt: "Quelle console portable Nintendo a-t-elle sortie en 1989 ?", choices: ["Game Boy", "Game Gear", "Lynx", "PSP"], banterHint: "Tetris a voyagé dans beaucoup de poches." },
          "fr-CA": { categoryTitle: "Écran de poche", prompt: "Quelle console portative Nintendo a sortie en 1989 ?", choices: ["Game Boy", "Game Gear", "Lynx", "PSP"], banterHint: "Tetris a voyagé dans bien des poches." },
          de: { categoryTitle: "Taschenbildschirm", prompt: "Welche Handheld-Konsole brachte Nintendo 1989 heraus?", choices: ["Game Boy", "Game Gear", "Lynx", "PSP"], banterHint: "Tetris reiste in vielen Taschen mit." },
        },
      }),
      q({
        id: "cq-e-genx-pdf",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-x",
        correctIndex: 2,
        sources: [{ label: "Adobe — PDF history" }, { label: "Encyclopaedia Britannica — document formats" }],
        text: {
          en: { categoryTitle: "Paperless Page", prompt: "What does PDF stand for?", choices: ["Public Data File", "Printed Document Form", "Portable Document Format", "Personal Disk Folder"], banterHint: "The page learned to travel." },
          fr: { categoryTitle: "Page sans papier", prompt: "Que signifie PDF ?", choices: ["Public Data File", "Printed Document Form", "Portable Document Format", "Personal Disk Folder"], banterHint: "La page a appris à voyager." },
          "fr-CA": { categoryTitle: "Page sans papier", prompt: "PDF veut dire quoi ?", choices: ["Public Data File", "Printed Document Form", "Portable Document Format", "Personal Disk Folder"], banterHint: "La page a appris à voyager." },
          de: { categoryTitle: "Seite ohne Papier", prompt: "Wofür steht PDF?", choices: ["Public Data File", "Printed Document Form", "Portable Document Format", "Personal Disk Folder"], banterHint: "Die Seite hat reisen gelernt." },
        },
      }),
      q({
        id: "cq-h-genx-ram",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-x",
        correctIndex: 1,
        sources: [{ label: "Computer History Museum — memory" }, { label: "Encyclopaedia Britannica — computer memory" }],
        text: {
          en: { categoryTitle: "Short Memory", prompt: "What does RAM stand for in a computer?", choices: ["Read And Modify", "Random Access Memory", "Rapid Archive Module", "Remote Access Mainframe"], banterHint: "Fast memory, and it forgets when the power goes." },
          fr: { categoryTitle: "Mémoire courte", prompt: "Que signifie RAM dans un ordinateur ?", choices: ["Read And Modify", "Random Access Memory", "Rapid Archive Module", "Remote Access Mainframe"], banterHint: "Une mémoire rapide, qui oublie quand le courant coupe." },
          "fr-CA": { categoryTitle: "Mémoire courte", prompt: "RAM, dans un ordinateur, ça veut dire quoi ?", choices: ["Read And Modify", "Random Access Memory", "Rapid Archive Module", "Remote Access Mainframe"], banterHint: "Une mémoire rapide, qui oublie quand le courant coupe." },
          de: { categoryTitle: "Kurzes Gedächtnis", prompt: "Wofür steht RAM in einem Computer?", choices: ["Read And Modify", "Random Access Memory", "Rapid Archive Module", "Remote Access Mainframe"], banterHint: "Schneller Speicher, und er vergisst ohne Strom." },
        },
      }),
      q({
        id: "cq-h-genx-cd",
        tier: "hard",
        topic: "music",
        generation: "gen-x",
        correctIndex: 0,
        sources: [{ label: "Philips / Sony — Compact Disc" }, { label: "Encyclopaedia Britannica — compact disc" }],
        text: {
          en: { categoryTitle: "Silver Circle", prompt: "What does CD stand for in the music format introduced in the early 1980s?", choices: ["Compact Disc", "Cassette Deck", "Crystal Drive", "Catalog Download"], banterHint: "A small mirror that held an album." },
          fr: { categoryTitle: "Cercle d'argent", prompt: "Que signifie CD dans le format musical lancé au début des années 1980 ?", choices: ["Compact Disc", "Cassette Deck", "Crystal Drive", "Catalog Download"], banterHint: "Un petit miroir qui tenait un album." },
          "fr-CA": { categoryTitle: "Cercle d'argent", prompt: "CD, pour le format musical du début des années 1980, veut dire quoi ?", choices: ["Compact Disc", "Cassette Deck", "Crystal Drive", "Catalog Download"], banterHint: "Un petit miroir qui contenait un album." },
          de: { categoryTitle: "Silberner Kreis", prompt: "Wofür steht CD beim Musikformat der frühen 1980er?", choices: ["Compact Disc", "Cassette Deck", "Crystal Drive", "Catalog Download"], banterHint: "Ein kleiner Spiegel, der ein Album hielt." },
        },
      }),
      q({
        id: "cq-e-genx-cassette",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-x",
        funny: true,
        technique: "wordplay",
        structure: "joke",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "Wound Up", prompt: "Why did the cassette feel shy?", choices: ["It was a little wound up", "It lost the pencil", "It hid in the walkman", "It skipped the chorus"], banterHint: "Side B still got a listen." },
          fr: { categoryTitle: "Un peu tendue", prompt: "Pourquoi la cassette se sentait-elle timide ?", choices: ["Elle était un peu tendue", "Elle a perdu le crayon", "Elle s'est cachée dans le baladeur", "Elle a sauté le refrain"], banterHint: "La face B a quand même eu son écoute." },
          "fr-CA": { categoryTitle: "Un peu tendue", prompt: "Pourquoi la cassette se sentait gênée ?", choices: ["Elle était un peu tendue", "Elle a perdu le crayon", "Elle s'est cachée dans le baladeur", "Elle a sauté le refrain"], banterHint: "La face B a quand même eu son écoute." },
          de: { categoryTitle: "Aufgedreht", prompt: "Warum war die Kassette schüchtern?", choices: ["Sie war etwas aufgedreht", "Sie verlor den Bleistift", "Sie versteckte sich im Walkman", "Sie übersprang den Refrain"], banterHint: "Seite B wurde trotzdem gehört." },
        },
      }),
      q({
        id: "cq-h-genx-blinky",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-x",
        structure: "colour",
        correctIndex: 0,
        sources: [{ label: "Bandai Namco — Pac-Man" }, { label: "Encyclopaedia Britannica — Pac-Man" }],
        text: {
          en: { categoryTitle: "Ghost Duty", prompt: "What colour is Blinky, the Pac-Man ghost?", choices: ["Red", "Pink", "Cyan", "Orange"], banterHint: "The other three ghosts wear the rest." },
          fr: { categoryTitle: "Service fantôme", prompt: "De quelle couleur est Blinky, le fantôme de Pac-Man ?", choices: ["Rouge", "Rose", "Cyan", "Orange"], banterHint: "Les trois autres portent le reste." },
          "fr-CA": { categoryTitle: "Service fantôme", prompt: "C'est quoi la couleur de Blinky, le fantôme de Pac-Man ?", choices: ["Rouge", "Rose", "Cyan", "Orange"], banterHint: "Les trois autres portent le reste." },
          de: { categoryTitle: "Geisterdienst", prompt: "Welche Farbe hat Blinky, der Pac-Man-Geist?", choices: ["Rot", "Rosa", "Cyan", "Orange"], banterHint: "Die anderen drei tragen den Rest." },
        },
      }),
      q({
        id: "cq-e-genx-tennis",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-x",
        structure: "colour",
        correctIndex: 0,
        sources: [{ label: "International Tennis Federation — rules" }, { label: "Encyclopaedia Britannica — tennis" }],
        text: {
          en: { categoryTitle: "Court", prompt: "What colour is a regulation tennis ball?", choices: ["Yellow", "White", "Green", "Orange"], banterHint: "Older balls were white. The rule now is the bright one." },
          fr: { categoryTitle: "Court", prompt: "De quelle couleur est une balle de tennis réglementaire ?", choices: ["Jaune", "Blanc", "Vert", "Orange"], banterHint: "Les anciennes balles étaient blanches. La règle est la vive." },
          "fr-CA": { categoryTitle: "Court", prompt: "C'est quoi la couleur d'une balle de tennis réglementaire ?", choices: ["Jaune", "Blanc", "Vert", "Orange"], banterHint: "Les anciennes balles étaient blanches. La règle est la vive." },
          de: { categoryTitle: "Platz", prompt: "Welche Farbe hat ein Tennisball nach den Regeln?", choices: ["Gelb", "Weiß", "Grün", "Orange"], banterHint: "Ältere Bälle waren weiß. Die Regel ist jetzt der helle." },
        },
      }),
      q({
        id: "cq-h-genx-web",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-x",
        structure: "when",
        fromStructure: "when",
        humorous: true,
        funny: true,
        injection: "misdirection",
        technique: "misdirection",
        correctIndex: 0,
        jokeWrongs: {
          2: {
            en: "January 1, when the calendar looked official",
            fr: "1 janvier, quand le calendrier avait l'air officiel",
            "fr-CA": "1er janvier, quand le calendrier avait l'air officiel",
            de: "1. Januar, als der Kalender offiziell aussah",
          },
          3: {
            en: "March 12, the day the idea cleared its throat",
            fr: "12 mars, le jour où l'idée s'est raclé la gorge",
            "fr-CA": "12 mars, le jour où l'idée s'est raclé la gorge",
            de: "12. März, der Tag, an dem die Idee sich räusperte",
          },
        },
        sources: [{ label: "CERN — World Wide Web" }, { label: "Encyclopaedia Britannica — World Wide Web" }],
        text: {
          en: { categoryTitle: "First Page", prompt: "When was the World Wide Web made available to the public?", choices: ["August 6, 1991", "August 6, 1989", "January 1, 1995", "March 12, 1989"], banterHint: "The idea is older. The public page is this date." },
          fr: { categoryTitle: "Première page", prompt: "Quand le Web a-t-il été ouvert au public ?", choices: ["6 août 1991", "6 août 1989", "1 janvier 1995", "12 mars 1989"], banterHint: "L'idée est plus vieille. La page publique est cette date." },
          "fr-CA": { categoryTitle: "Première page", prompt: "Le Web a été ouvert au public quand ?", choices: ["6 août 1991", "6 août 1989", "1 janvier 1995", "12 mars 1989"], banterHint: "L'idée est plus vieille. La page publique est cette date." },
          de: { categoryTitle: "Erste Seite", prompt: "Wann wurde das World Wide Web der Öffentlichkeit zugänglich?", choices: ["6. August 1991", "6. August 1989", "1. Januar 1995", "12. März 1989"], banterHint: "Die Idee ist älter. Die öffentliche Seite hat dieses Datum." },
        },
      }),
      q({
        id: "cq-e-genx-redspot",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-x",
        correctIndex: 0,
        sources: [{ label: "NASA — Jupiter" }, { label: "Encyclopaedia Britannica — Great Red Spot" }],
        text: {
          en: { categoryTitle: "Storm", prompt: "Which planet is known for the Great Red Spot?", choices: ["Jupiter", "Mars", "Saturn", "Venus"], banterHint: "The spot is a storm that has outlasted a lot of weather reports." },
          fr: { categoryTitle: "Tempête", prompt: "Quelle planète est connue pour la Grande Tache rouge ?", choices: ["Jupiter", "Mars", "Saturne", "Vénus"], banterHint: "La tache est une tempête plus vieille que bien des bulletins." },
          "fr-CA": { categoryTitle: "Tempête", prompt: "Quelle planète est connue pour la Grande Tache rouge ?", choices: ["Jupiter", "Mars", "Saturne", "Vénus"], banterHint: "La tache est une tempête plus vieille que bien des bulletins." },
          de: { categoryTitle: "Sturm", prompt: "Welcher Planet ist für den Großen Roten Fleck bekannt?", choices: ["Jupiter", "Mars", "Saturn", "Venus"], banterHint: "Der Fleck ist ein Sturm, der viele Wetterberichte überdauert hat." },
        },
      }),
      q({
        id: "cq-h-genx-cdsale",
        tier: "hard",
        topic: "music",
        generation: "gen-x",
        correctIndex: 0,
        sources: [{ label: "Philips — compact disc history" }, { label: "Encyclopaedia Britannica — compact disc" }],
        text: {
          en: { categoryTitle: "Silver Disc", prompt: "In which year did the compact disc first go on sale?", choices: ["1982", "1977", "1988", "1991"], banterHint: "The shiny circle arrived before the playlist apps." },
          fr: { categoryTitle: "Disque argenté", prompt: "En quelle année le disque compact a-t-il été mis en vente ?", choices: ["1982", "1977", "1988", "1991"], banterHint: "Le cercle brillant est arrivé avant les listes d'écoute." },
          "fr-CA": { categoryTitle: "Disque argenté", prompt: "En quelle année le disque compact a été mis en vente ?", choices: ["1982", "1977", "1988", "1991"], banterHint: "Le cercle brillant est arrivé avant les listes de lecture." },
          de: { categoryTitle: "Silberne Scheibe", prompt: "In welchem Jahr kam die Compact Disc erstmals in den Handel?", choices: ["1982", "1977", "1988", "1991"], banterHint: "Der glänzende Kreis kam vor den Playlists." },
        },
      }),
    ],
  },
  {
    bot: "Creator Gen Y",
    generation: "gen-y",
    questions: [
      q({
        id: "cq-e-geny-wiki",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-y",
        correctIndex: 0,
        sources: [{ label: "Wikimedia Foundation — Wikipedia history" }, { label: "Encyclopaedia Britannica — Wikipedia" }],
        text: {
          en: { categoryTitle: "Open Book", prompt: "Which website, launched in 2001, lets people write encyclopedia articles together?", choices: ["Wikipedia", "MySpace", "GeoCities", "AltaVista"], banterHint: "The edit button is the whole idea." },
          fr: { categoryTitle: "Livre ouvert", prompt: "Quel site, lancé en 2001, permet d'écrire des articles d'encyclopédie à plusieurs ?", choices: ["Wikipédia", "MySpace", "GeoCities", "AltaVista"], banterHint: "Le bouton modifier est toute l'idée." },
          "fr-CA": { categoryTitle: "Livre ouvert", prompt: "Quel site, lancé en 2001, permet d'écrire des articles d'encyclopédie ensemble ?", choices: ["Wikipédia", "MySpace", "GeoCities", "AltaVista"], banterHint: "Le bouton modifier, c'est toute l'idée." },
          de: { categoryTitle: "Offenes Buch", prompt: "Welche Website, gestartet 2001, lässt Menschen Enzyklopädie-Artikel gemeinsam schreiben?", choices: ["Wikipedia", "MySpace", "GeoCities", "AltaVista"], banterHint: "Der Bearbeiten-Knopf ist die ganze Idee." },
        },
      }),
      q({
        id: "cq-e-geny-sms",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-y",
        correctIndex: 1,
        sources: [{ label: "GSM Association — SMS" }, { label: "Encyclopaedia Britannica — text messaging" }],
        text: {
          en: { categoryTitle: "Short Note", prompt: "What does SMS stand for?", choices: ["Simple Mail Switch", "Short Message Service", "Secure Media Stream", "Standard Mobile Signal"], banterHint: "One hundred and sixty characters, and a lot of plans." },
          fr: { categoryTitle: "Note courte", prompt: "Que signifie SMS ?", choices: ["Simple Mail Switch", "Short Message Service", "Secure Media Stream", "Standard Mobile Signal"], banterHint: "Cent soixante caractères, et beaucoup de rendez-vous." },
          "fr-CA": { categoryTitle: "Note courte", prompt: "SMS veut dire quoi ?", choices: ["Simple Mail Switch", "Short Message Service", "Secure Media Stream", "Standard Mobile Signal"], banterHint: "Cent soixante caractères, et beaucoup de rendez-vous." },
          de: { categoryTitle: "Kurze Notiz", prompt: "Wofür steht SMS?", choices: ["Simple Mail Switch", "Short Message Service", "Secure Media Stream", "Standard Mobile Signal"], banterHint: "Einhundertsechzig Zeichen, und viele Verabredungen." },
        },
      }),
      q({
        id: "cq-h-geny-iphone",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-y",
        correctIndex: 0,
        sources: [{ label: "Apple — iPhone announcement, 2007" }, { label: "Encyclopaedia Britannica — smartphone" }],
        text: {
          en: { categoryTitle: "Pocket Computer", prompt: "Which company released the first iPhone in 2007?", choices: ["Apple", "Nokia", "BlackBerry", "Motorola"], banterHint: "The keyboard moved onto the glass." },
          fr: { categoryTitle: "Ordinateur de poche", prompt: "Quelle société a sorti le premier iPhone en 2007 ?", choices: ["Apple", "Nokia", "BlackBerry", "Motorola"], banterHint: "Le clavier est passé sur la vitre." },
          "fr-CA": { categoryTitle: "Ordinateur de poche", prompt: "Quelle compagnie a lancé le premier iPhone en 2007 ?", choices: ["Apple", "Nokia", "BlackBerry", "Motorola"], banterHint: "Le clavier est passé sur la vitre." },
          de: { categoryTitle: "Taschengerät", prompt: "Welche Firma brachte 2007 das erste iPhone heraus?", choices: ["Apple", "Nokia", "BlackBerry", "Motorola"], banterHint: "Die Tastatur wanderte aufs Glas." },
        },
      }),
      q({
        id: "cq-h-geny-facebook",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-y",
        correctIndex: 2,
        sources: [{ label: "Meta — company history" }, { label: "Encyclopaedia Britannica — Facebook" }],
        text: {
          en: { categoryTitle: "Open Registration", prompt: "In which year did Facebook open registration beyond schools to anyone 13 or older?", choices: ["2004", "2005", "2006", "2008"], banterHint: "The campus gate came down in September." },
          fr: { categoryTitle: "Inscription ouverte", prompt: "En quelle année Facebook a-t-il ouvert l'inscription au-delà des écoles, à toute personne de 13 ans ou plus ?", choices: ["2004", "2005", "2006", "2008"], banterHint: "La porte du campus est tombée en septembre." },
          "fr-CA": { categoryTitle: "Inscription ouverte", prompt: "En quelle année Facebook a ouvert l'inscription au-delà des écoles, à toute personne de 13 ans ou plus ?", choices: ["2004", "2005", "2006", "2008"], banterHint: "La porte du campus est tombée en septembre." },
          de: { categoryTitle: "Offene Anmeldung", prompt: "In welchem Jahr öffnete Facebook die Anmeldung über Schulen hinaus für alle ab 13?", choices: ["2004", "2005", "2006", "2008"], banterHint: "Das Campus-Tor fiel im September." },
        },
      }),
      q({
        id: "cq-h-geny-inbox",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-y",
        funny: true,
        technique: "wordplay",
        structure: "joke",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "Still Calm", prompt: "Why did the inbox stay calm?", choices: ["It knew how to keep its letters", "It deleted the morning", "It hid the password", "It missed the send button"], banterHint: "The unread pile stayed polite." },
          fr: { categoryTitle: "Toujours calme", prompt: "Pourquoi la boîte de réception est-elle restée calme ?", choices: ["Elle savait garder ses lettres", "Elle a effacé le matin", "Elle a caché le mot de passe", "Elle a raté le bouton envoyer"], banterHint: "La pile non lue est restée polie." },
          "fr-CA": { categoryTitle: "Toujours calme", prompt: "Pourquoi la boîte de réception est restée calme ?", choices: ["Elle savait garder ses lettres", "Elle a effacé le matin", "Elle a caché le mot de passe", "Elle a raté le bouton envoyer"], banterHint: "La pile non lue est restée polie." },
          de: { categoryTitle: "Immer ruhig", prompt: "Warum blieb der Posteingang ruhig?", choices: ["Er wusste, wie man Briefe behält", "Er löschte den Morgen", "Er versteckte das Passwort", "Er verpasste den Senden-Knopf"], banterHint: "Der ungelesene Stapel blieb höflich." },
        },
      }),
      q({
        id: "cq-h-geny-ocean",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-y",
        structure: "colour",
        correctIndex: 0,
        sources: [{ label: "Paramount — Titanic (1997)" }, { label: "Encyclopaedia Britannica — Titanic, film" }],
        text: {
          en: { categoryTitle: "Jewel Case", prompt: "What colour is the Heart of the Ocean in the film Titanic?", choices: ["Blue", "Green", "Red", "Yellow"], banterHint: "The necklace kept that one shade." },
          fr: { categoryTitle: "Écrin", prompt: "De quelle couleur est le Cœur de l'océan dans le film Titanic ?", choices: ["Bleu", "Vert", "Rouge", "Jaune"], banterHint: "Le collier a gardé cette seule teinte." },
          "fr-CA": { categoryTitle: "Écrin", prompt: "C'est quoi la couleur du Cœur de l'océan dans le film Titanic ?", choices: ["Bleu", "Vert", "Rouge", "Jaune"], banterHint: "Le collier a gardé cette seule teinte." },
          de: { categoryTitle: "Schmucketui", prompt: "Welche Farbe hat das Herz des Ozeans im Film Titanic?", choices: ["Blau", "Grün", "Rot", "Gelb"], banterHint: "Die Kette behielt genau diesen Ton." },
        },
      }),
      q({
        id: "cq-e-geny-potter",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-y",
        structure: "when",
        correctIndex: 0,
        sources: [{ label: "Encyclopaedia Britannica — J. K. Rowling" }, { label: "British Library — Harry Potter" }],
        text: {
          en: { categoryTitle: "First Book", prompt: "When was the first Harry Potter book published in the United Kingdom?", choices: ["1997", "1995", "1999", "2001"], banterHint: "The school term in the book starts later than the book itself." },
          fr: { categoryTitle: "Premier livre", prompt: "Quand le premier livre Harry Potter a-t-il été publié au Royaume-Uni ?", choices: ["1997", "1995", "1999", "2001"], banterHint: "La rentrée dans le livre arrive après le livre." },
          "fr-CA": { categoryTitle: "Premier livre", prompt: "Le premier livre Harry Potter a été publié au Royaume-Uni quand ?", choices: ["1997", "1995", "1999", "2001"], banterHint: "La rentrée dans le livre arrive après le livre." },
          de: { categoryTitle: "Erstes Buch", prompt: "Wann erschien das erste Harry-Potter-Buch im Vereinigten Königreich?", choices: ["1997", "1995", "1999", "2001"], banterHint: "Der Schulanfang im Buch kommt nach dem Buch." },
        },
      }),
      q({
        id: "cq-h-geny-euro",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-y",
        structure: "when",
        fromStructure: "when",
        humorous: true,
        funny: true,
        injection: "wordplay",
        technique: "wordplay",
        correctIndex: 0,
        jokeWrongs: {
          2: {
            en: "2004, when the coins learned to juggle",
            fr: "2004, quand les pièces ont appris à jongler",
            "fr-CA": "2004, quand les pièces ont appris à jongler",
            de: "2004, als die Münzen jonglieren lernten",
          },
          3: {
            en: "July, halfway through a very long receipt",
            fr: "Juillet, à mi-chemin d'un très long reçu",
            "fr-CA": "Juillet, à mi-chemin d'un très long reçu",
            de: "Juli, auf halbem Weg durch eine sehr lange Quittung",
          },
        },
        sources: [{ label: "European Central Bank — euro cash" }, { label: "Encyclopaedia Britannica — euro" }],
        text: {
          en: { categoryTitle: "Notes and Coins", prompt: "When did euro banknotes and coins enter circulation?", choices: ["January 1, 2002", "January 1, 1999", "January 1, 2004", "July 1, 2002"], banterHint: "The currency had a birthday before the cash did." },
          fr: { categoryTitle: "Billets et pièces", prompt: "Quand les billets et les pièces en euros sont-ils entrés en circulation ?", choices: ["1 janvier 2002", "1 janvier 1999", "1 janvier 2004", "1 juillet 2002"], banterHint: "La monnaie a eu un anniversaire avant les billets." },
          "fr-CA": { categoryTitle: "Billets et pièces", prompt: "Les billets et les pièces en euros sont entrés en circulation quand ?", choices: ["1 janvier 2002", "1 janvier 1999", "1 janvier 2004", "1 juillet 2002"], banterHint: "La monnaie a eu un anniversaire avant les billets." },
          de: { categoryTitle: "Scheine und Münzen", prompt: "Wann kamen Euro-Banknoten und Münzen in Umlauf?", choices: ["1. Januar 2002", "1. Januar 1999", "1. Januar 2004", "1. Juli 2002"], banterHint: "Die Währung hatte einen Geburtstag vor dem Bargeld." },
        },
      }),
      q({
        id: "cq-e-geny-canberra",
        tier: "easy",
        topic: "geography",
        generation: "gen-y",
        correctIndex: 0,
        sources: [{ label: "Australian Government — capital" }, { label: "Encyclopaedia Britannica — Canberra" }],
        text: {
          en: { categoryTitle: "Capital", prompt: "What is the capital city of Australia?", choices: ["Canberra", "Sydney", "Melbourne", "Brisbane"], banterHint: "The harbour city is famous. The capital is the planned one." },
          fr: { categoryTitle: "Capitale", prompt: "Quelle est la capitale de l'Australie ?", choices: ["Canberra", "Sydney", "Melbourne", "Brisbane"], banterHint: "La ville du port est célèbre. La capitale est celle qui a été planifiée." },
          "fr-CA": { categoryTitle: "Capitale", prompt: "C'est quoi la capitale de l'Australie ?", choices: ["Canberra", "Sydney", "Melbourne", "Brisbane"], banterHint: "La ville du port est célèbre. La capitale est celle qui a été planifiée." },
          de: { categoryTitle: "Hauptstadt", prompt: "Was ist die Hauptstadt Australiens?", choices: ["Canberra", "Sydney", "Melbourne", "Brisbane"], banterHint: "Die Hafenstadt ist berühmt. Die Hauptstadt ist die geplante." },
        },
      }),
      q({
        id: "cq-h-geny-html",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-y",
        correctIndex: 0,
        sources: [{ label: "W3C — HTML" }, { label: "Encyclopaedia Britannica — HTML" }],
        text: {
          en: { categoryTitle: "Page Language", prompt: "What does HTML stand for?", choices: ["HyperText Markup Language", "High Transfer Mail Link", "Home Tool Markup Language", "Hyperlink Text Main Language"], banterHint: "The page you are reading is written in it." },
          fr: { categoryTitle: "Langage de page", prompt: "Que signifie le sigle HTML ?", choices: ["HyperText Markup Language", "High Transfer Mail Link", "Home Tool Markup Language", "Hyperlink Text Main Language"], banterHint: "La page que tu lis est écrite avec." },
          "fr-CA": { categoryTitle: "Langage de page", prompt: "HTML veut dire quoi ?", choices: ["HyperText Markup Language", "High Transfer Mail Link", "Home Tool Markup Language", "Hyperlink Text Main Language"], banterHint: "La page que tu lis est écrite avec." },
          de: { categoryTitle: "Seitensprache", prompt: "Wofür steht HTML?", choices: ["HyperText Markup Language", "High Transfer Mail Link", "Home Tool Markup Language", "Hyperlink Text Main Language"], banterHint: "Die Seite, die du liest, ist darin geschrieben." },
        },
      }),
    ],
  },
  {
    bot: "Creator Gen Z",
    generation: "gen-z",
    questions: [
      q({
        id: "cq-e-genz-gif",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-z",
        correctIndex: 0,
        sources: [{ label: "CompuServe — GIF specification" }, { label: "Encyclopaedia Britannica — GIF" }],
        text: {
          en: { categoryTitle: "Tiny Loop", prompt: "What does GIF stand for?", choices: ["Graphics Interchange Format", "Global Image File", "Grouped Internet Frame", "General Icon Folder"], banterHint: "A picture that refuses to sit still." },
          fr: { categoryTitle: "Petite boucle", prompt: "Que signifie GIF ?", choices: ["Graphics Interchange Format", "Global Image File", "Grouped Internet Frame", "General Icon Folder"], banterHint: "Une image qui refuse de rester sage." },
          "fr-CA": { categoryTitle: "Petite boucle", prompt: "GIF veut dire quoi ?", choices: ["Graphics Interchange Format", "Global Image File", "Grouped Internet Frame", "General Icon Folder"], banterHint: "Une image qui refuse de rester tranquille." },
          de: { categoryTitle: "Kleine Schleife", prompt: "Wofür steht GIF?", choices: ["Graphics Interchange Format", "Global Image File", "Grouped Internet Frame", "General Icon Folder"], banterHint: "Ein Bild, das nicht stillsitzen will." },
        },
      }),
      q({
        id: "cq-e-genz-vr",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-z",
        correctIndex: 1,
        sources: [{ label: "IEEE — virtual reality overview" }, { label: "Encyclopaedia Britannica — virtual reality" }],
        text: {
          en: { categoryTitle: "Headset", prompt: "What does VR stand for in a headset?", choices: ["Video Relay", "Virtual Reality", "Visual Radio", "Vector Render"], banterHint: "The room stays put. The view does not." },
          fr: { categoryTitle: "Casque", prompt: "Que signifie VR sur un casque ?", choices: ["Video Relay", "Virtual Reality", "Visual Radio", "Vector Render"], banterHint: "La pièce reste là. La vue, non." },
          "fr-CA": { categoryTitle: "Casque", prompt: "VR, sur un casque, veut dire quoi ?", choices: ["Video Relay", "Virtual Reality", "Visual Radio", "Vector Render"], banterHint: "La pièce reste là. Pas la vue." },
          de: { categoryTitle: "Kopfhörerbrille", prompt: "Wofür steht VR bei einem Headset?", choices: ["Video Relay", "Virtual Reality", "Visual Radio", "Vector Render"], banterHint: "Der Raum bleibt. Die Sicht nicht." },
        },
      }),
      q({
        id: "cq-h-genz-bytedance",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-z",
        correctIndex: 2,
        sources: [{ label: "ByteDance — company overview" }, { label: "Encyclopaedia Britannica — TikTok" }],
        text: {
          en: { categoryTitle: "Short Video", prompt: "Which company owns TikTok?", choices: ["Meta", "Google", "ByteDance", "Snap"], banterHint: "The app is the famous part. The company is quieter." },
          fr: { categoryTitle: "Vidéo courte", prompt: "Quelle société possède TikTok ?", choices: ["Meta", "Google", "ByteDance", "Snap"], banterHint: "L'appli est la partie célèbre. La société, moins." },
          "fr-CA": { categoryTitle: "Vidéo courte", prompt: "Quelle compagnie possède TikTok ?", choices: ["Meta", "Google", "ByteDance", "Snap"], banterHint: "L'appli est la partie connue. La compagnie, moins." },
          de: { categoryTitle: "Kurzvideo", prompt: "Welche Firma besitzt TikTok?", choices: ["Meta", "Google", "ByteDance", "Snap"], banterHint: "Die App ist der berühmte Teil. Die Firma ist leiser." },
        },
      }),
      q({
        id: "cq-h-genz-hashtag",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-z",
        correctIndex: 0,
        sources: [{ label: "Oxford English Dictionary — hashtag" }, { label: "Encyclopaedia Britannica — social media" }],
        text: {
          en: { categoryTitle: "Pound Sign", prompt: "What is the name of the # symbol when it groups posts on social media?", choices: ["A hashtag", "An asterisk", "A caret", "A tilde"], banterHint: "One mark, and the posts find each other." },
          fr: { categoryTitle: "Dièse", prompt: "Comment appelle-t-on le symbole # quand il regroupe des posts sur les réseaux sociaux ?", choices: ["Un hashtag", "Un astérisque", "Un caret", "Un tilde"], banterHint: "Une marque, et les posts se retrouvent." },
          "fr-CA": { categoryTitle: "Dièse", prompt: "Comment on appelle le symbole # quand il regroupe des publications sur les réseaux sociaux ?", choices: ["Un hashtag", "Un astérisque", "Un caret", "Un tilde"], banterHint: "Une marque, et les publications se retrouvent." },
          de: { categoryTitle: "Raute", prompt: "Wie heißt das Zeichen #, wenn es Beiträge in sozialen Medien bündelt?", choices: ["Ein Hashtag", "Ein Sternchen", "Ein Caret", "Eine Tilde"], banterHint: "Ein Zeichen, und die Beiträge finden sich." },
        },
      }),
      q({
        id: "cq-e-genz-emoji",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-z",
        funny: true,
        technique: "misdirection",
        structure: "joke",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "One Eye", prompt: "Why did the emoji wink?", choices: ["It had a point to make", "It lost the other eye", "It hid the keyboard", "It missed the chat"], banterHint: "The message still landed kindly." },
          fr: { categoryTitle: "Un œil", prompt: "Pourquoi l'emoji a-t-il fait un clin d'œil ?", choices: ["Il avait quelque chose à dire", "Il a perdu l'autre œil", "Il a caché le clavier", "Il a raté la discussion"], banterHint: "Le message est quand même arrivé gentiment." },
          "fr-CA": { categoryTitle: "Un œil", prompt: "Pourquoi l'emoji a fait un clin d'œil ?", choices: ["Il avait quelque chose à dire", "Il a perdu l'autre œil", "Il a caché le clavier", "Il a manqué la discussion"], banterHint: "Le message est quand même arrivé gentiment." },
          de: { categoryTitle: "Ein Auge", prompt: "Warum zwinkerte das Emoji?", choices: ["Es hatte etwas zu sagen", "Es verlor das andere Auge", "Es versteckte die Tastatur", "Es verpasste den Chat"], banterHint: "Die Nachricht kam trotzdem freundlich an." },
        },
      }),
      q({
        id: "cq-e-genz-spotify",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-z",
        structure: "colour",
        correctIndex: 0,
        sources: [{ label: "Spotify — brand" }, { label: "Spotify Newsroom — company" }],
        text: {
          en: { categoryTitle: "Logo Circle", prompt: "What colour is the circle in the Spotify logo?", choices: ["Green", "Blue", "Red", "Yellow"], banterHint: "The sound waves sit on top of it." },
          fr: { categoryTitle: "Cercle du logo", prompt: "De quelle couleur est le cercle du logo Spotify ?", choices: ["Vert", "Bleu", "Rouge", "Jaune"], banterHint: "Les ondes sonores sont posées dessus." },
          "fr-CA": { categoryTitle: "Cercle du logo", prompt: "C'est quoi la couleur du cercle dans le logo Spotify ?", choices: ["Vert", "Bleu", "Rouge", "Jaune"], banterHint: "Les ondes sonores sont posées dessus." },
          de: { categoryTitle: "Logo-Kreis", prompt: "Welche Farbe hat der Kreis im Spotify-Logo?", choices: ["Grün", "Blau", "Rot", "Gelb"], banterHint: "Die Schallwellen liegen darauf." },
        },
      }),
      q({
        id: "cq-e-genz-instagram",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-z",
        structure: "when",
        correctIndex: 0,
        sources: [{ label: "Encyclopaedia Britannica — Instagram" }, { label: "Meta — Instagram" }],
        text: {
          en: { categoryTitle: "First Post", prompt: "When was Instagram launched?", choices: ["2010", "2008", "2012", "2014"], banterHint: "The square photos showed up in that year." },
          fr: { categoryTitle: "Premier post", prompt: "Quand Instagram a-t-il été lancé ?", choices: ["2010", "2008", "2012", "2014"], banterHint: "Les photos carrées sont arrivées cette année-là." },
          "fr-CA": { categoryTitle: "Premier post", prompt: "Instagram a été lancé quand ?", choices: ["2010", "2008", "2012", "2014"], banterHint: "Les photos carrées sont arrivées cette année-là." },
          de: { categoryTitle: "Erster Beitrag", prompt: "Wann wurde Instagram gestartet?", choices: ["2010", "2008", "2012", "2014"], banterHint: "Die quadratischen Fotos kamen in dem Jahr." },
        },
      }),
      q({
        id: "cq-e-genz-bus",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-z",
        structure: "colour",
        fromStructure: "colour",
        humorous: true,
        funny: true,
        injection: "callback",
        technique: "callback",
        correctIndex: 0,
        jokeWrongs: {
          2: {
            en: "Blue, if the ocean is driving the route",
            fr: "Bleu, si l'océan conduit la ligne",
            "fr-CA": "Bleu, si l'océan conduit la ligne",
            de: "Blau, wenn der Ozean die Strecke fährt",
          },
          3: {
            en: "White, after a very thorough wash",
            fr: "Blanc, après un lavage très soigné",
            "fr-CA": "Blanc, après un lavage très soigné",
            de: "Weiß, nach einer sehr gründlichen Wäsche",
          },
        },
        sources: [{ label: "National Highway Traffic Safety Administration — school bus" }, { label: "Encyclopaedia Britannica — school bus" }],
        text: {
          en: { categoryTitle: "The Stop Arm", prompt: "What colour is a standard school bus in the United States?", choices: ["Yellow", "Orange", "Blue", "White"], banterHint: "The stop arm is the clue. Kids spot that paint from the curb." },
          fr: { categoryTitle: "Le bras d'arrêt", prompt: "De quelle couleur est un autobus scolaire standard aux États-Unis ?", choices: ["Jaune", "Orange", "Bleu", "Blanc"], banterHint: "Le bras d'arrêt est l'indice. Les enfants voient cette peinture du trottoir." },
          "fr-CA": { categoryTitle: "Le bras d'arrêt", prompt: "C'est quoi la couleur d'un autobus scolaire standard aux États-Unis ?", choices: ["Jaune", "Orange", "Bleu", "Blanc"], banterHint: "Le bras d'arrêt est l'indice. Les enfants voient cette peinture du trottoir." },
          de: { categoryTitle: "Der Stopparm", prompt: "Welche Farbe hat ein üblicher Schulbus in den USA?", choices: ["Gelb", "Orange", "Blau", "Weiß"], banterHint: "Der Stopparm ist der Hinweis. Kinder sehen diese Farbe vom Bordstein." },
        },
      }),
      q({
        id: "cq-e-genz-eleven",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-z",
        correctIndex: 0,
        sources: [{ label: "IFAB — Laws of the Game" }, { label: "FIFA — laws of the game" }],
        text: {
          en: { categoryTitle: "Starting Side", prompt: "How many players from one team are on the field in a standard football match?", choices: ["11", "9", "10", "15"], banterHint: "The bench watches. The count is the ones on the grass." },
          fr: { categoryTitle: "Équipe de départ", prompt: "Combien de joueurs d'une équipe sont sur le terrain dans un match de football standard ?", choices: ["11", "9", "10", "15"], banterHint: "Le banc regarde. Le compte, ce sont ceux sur l'herbe." },
          "fr-CA": { categoryTitle: "Équipe de départ", prompt: "Dans un match de soccer standard, une équipe a combien de joueurs sur le terrain ?", choices: ["11", "9", "10", "15"], banterHint: "Le banc regarde. Le compte, ce sont ceux sur le gazon." },
          de: { categoryTitle: "Startelf", prompt: "Wie viele Spieler einer Mannschaft stehen bei einem üblichen Fußballspiel auf dem Feld?", choices: ["11", "9", "10", "15"], banterHint: "Die Bank schaut zu. Gezählt werden die auf dem Rasen." },
        },
      }),
      q({
        id: "cq-h-genz-mohs",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-z",
        correctIndex: 0,
        sources: [{ label: "Encyclopaedia Britannica — Mohs scale" }, { label: "Mindat — Mohs hardness" }],
        text: {
          en: { categoryTitle: "Hardness", prompt: "What is the hardest natural mineral on the Mohs scale?", choices: ["Diamond", "Quartz", "Topaz", "Corundum"], banterHint: "The scale stops at ten. This one sits there." },
          fr: { categoryTitle: "Dureté", prompt: "Quel est le minéral naturel le plus dur sur l'échelle de Mohs ?", choices: ["Le diamant", "Le quartz", "La topaze", "Le corindon"], banterHint: "L'échelle s'arrête à dix. Celui-ci y est." },
          "fr-CA": { categoryTitle: "Dureté", prompt: "C'est quoi le minéral naturel le plus dur sur l'échelle de Mohs ?", choices: ["Le diamant", "Le quartz", "La topaze", "Le corindon"], banterHint: "L'échelle arrête à dix. Celui-ci est là." },
          de: { categoryTitle: "Härte", prompt: "Welches natürliche Mineral ist auf der Mohs-Skala das härteste?", choices: ["Diamant", "Quarz", "Topas", "Korund"], banterHint: "Die Skala endet bei zehn. Dieses sitzt dort." },
        },
      }),
    ],
  },
  {
    bot: "Creator Gen Alpha",
    generation: "gen-alpha",
    questions: [
      q({
        id: "cq-e-alpha-cat",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-alpha",
        funny: true,
        technique: "wordplay",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "Quiz Host", prompt: "What do you call a cat who hosts the quiz?", choices: ["The purr-son in charge", "A scaredy cat", "A copycat", "A catnap"], banterHint: "It still lands on its feet." },
          fr: { categoryTitle: "Hôte du quiz", prompt: "Comment appelle-t-on un chat qui présente le quiz ?", choices: ["Le ron-ron en chef", "Un chat peureux", "Un copieur", "Une sieste de chat"], banterHint: "Il retombe quand même sur ses pattes." },
          "fr-CA": { categoryTitle: "Animateur du quiz", prompt: "Comment on appelle un chat qui anime le quiz ?", choices: ["Le ronron en charge", "Un chat peureux", "Un copieur", "Un somme de chat"], banterHint: "Il retombe quand même sur ses pattes." },
          de: { categoryTitle: "Quiz-Katze", prompt: "Wie nennt man eine Katze, die das Quiz moderiert?", choices: ["Die Schnurr-Chefin", "Eine Angsthase", "Ein Nachmacher", "Ein Nickerchen"], banterHint: "Sie landet trotzdem auf den Pfoten." },
        },
      }),
      q({
        id: "cq-e-alpha-backpack",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-alpha",
        funny: true,
        technique: "misdirection",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "Good Day", prompt: "Why did the backpack look proud?", choices: ["It was carrying a good day", "It ate the homework", "It missed the bus", "It hid the map"], banterHint: "Every book got a lift." },
          fr: { categoryTitle: "Belle journée", prompt: "Pourquoi le sac à dos avait-il l'air fier ?", choices: ["Il portait une bonne journée", "Il a mangé les devoirs", "Il a raté le bus", "Il a caché la carte"], banterHint: "Chaque livre a eu un coup de main." },
          "fr-CA": { categoryTitle: "Belle journée", prompt: "Pourquoi le sac à dos avait l'air fier ?", choices: ["Il portait une bonne journée", "Il a mangé les devoirs", "Il a manqué l'autobus", "Il a caché la carte"], banterHint: "Chaque livre a eu un coup de pouce." },
          de: { categoryTitle: "Guter Tag", prompt: "Warum sah der Rucksack stolz aus?", choices: ["Er trug einen guten Tag", "Er aß die Hausaufgaben", "Er verpasste den Bus", "Er versteckte die Karte"], banterHint: "Jedes Buch bekam eine Mitfahrgelegenheit." },
        },
      }),
      q({
        id: "cq-h-alpha-pencil",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-alpha",
        funny: true,
        technique: "wordplay",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "Team Player", prompt: "Why did the pencil join the team?", choices: ["It could draw a crowd", "It rolled away", "It hid in the case", "It lost its cap"], banterHint: "The eraser had its back." },
          fr: { categoryTitle: "Esprit d'équipe", prompt: "Pourquoi le crayon a-t-il rejoint l'équipe ?", choices: ["Il savait attirer la foule", "Il a roulé plus loin", "Il s'est caché dans la trousse", "Il a perdu son capuchon"], banterHint: "La gomme veillait sur lui." },
          "fr-CA": { categoryTitle: "Esprit d'équipe", prompt: "Pourquoi le crayon s'est joint à l'équipe ?", choices: ["Il savait attirer la gang", "Il a roulé plus loin", "Il s'est caché dans l'étui", "Il a perdu son capuchon"], banterHint: "L'efface veillait sur lui." },
          de: { categoryTitle: "Mannschaft", prompt: "Warum trat der Bleistift der Mannschaft bei?", choices: ["Er konnte ein Publikum anziehen", "Er rollte weg", "Er versteckte sich im Etui", "Er verlor seine Kappe"], banterHint: "Der Radiergummi hielt ihm den Rücken frei." },
        },
      }),
      q({
        id: "cq-h-alpha-bookmark",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-alpha",
        funny: true,
        technique: "callback",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "Still Here", prompt: "Why did the bookmark stay calm in the story?", choices: ["It always held its place", "It tore the page", "It skipped the ending", "It hid the title"], banterHint: "Chapter after chapter, still kind." },
          fr: { categoryTitle: "Toujours là", prompt: "Pourquoi le marque-page restait-il calme dans l'histoire ?", choices: ["Il gardait toujours sa place", "Il a déchiré la page", "Il a sauté la fin", "Il a caché le titre"], banterHint: "Chapitre après chapitre, toujours gentil." },
          "fr-CA": { categoryTitle: "Toujours là", prompt: "Pourquoi le signet restait calme dans l'histoire ?", choices: ["Il gardait toujours sa place", "Il a déchiré la page", "Il a sauté la fin", "Il a caché le titre"], banterHint: "Chapitre après chapitre, toujours gentil." },
          de: { categoryTitle: "Immer noch da", prompt: "Warum blieb das Lesezeichen in der Geschichte ruhig?", choices: ["Es behielt immer seinen Platz", "Es zerriss die Seite", "Es übersprang das Ende", "Es versteckte den Titel"], banterHint: "Kapitel für Kapitel, immer freundlich." },
        },
      }),
      q({
        id: "cq-e-alpha-frog",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-alpha",
        funny: true,
        technique: "misdirection",
        structure: "colour",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "Open Mic", prompt: "What colour is a frog on open-mic night?", choices: ["Green", "Purple", "Orange", "Silver"], banterHint: "The room stayed ribbiting." },
          fr: { categoryTitle: "Scène ouverte", prompt: "De quelle couleur est une grenouille le soir du micro ouvert ?", choices: ["Vert", "Violet", "Orange", "Argent"], banterHint: "La salle est restée croassante." },
          "fr-CA": { categoryTitle: "Scène ouverte", prompt: "C'est quoi la couleur d'une grenouille le soir du micro ouvert ?", choices: ["Vert", "Violet", "Orange", "Argent"], banterHint: "La salle est restée croassante." },
          de: { categoryTitle: "Offenes Mikro", prompt: "Welche Farbe hat ein Frosch am Open-Mic-Abend?", choices: ["Grün", "Lila", "Orange", "Silber"], banterHint: "Der Raum blieb quakend freundlich." },
        },
      }),
      q({
        id: "cq-h-alpha-planets",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-alpha",
        correctIndex: 0,
        sources: [{ label: "NASA — solar system" }, { label: "International Astronomical Union — planets" }],
        text: {
          en: { categoryTitle: "Home System", prompt: "How many planets are in our solar system?", choices: ["8", "9", "7", "10"], banterHint: "The lineup got shorter in 2006, and it stayed kind." },
          fr: { categoryTitle: "Système maison", prompt: "Combien de planètes compte notre système solaire ?", choices: ["8", "9", "7", "10"], banterHint: "La liste a raccourci en 2006, et elle est restée gentille." },
          "fr-CA": { categoryTitle: "Système maison", prompt: "Notre système solaire compte combien de planètes ?", choices: ["8", "9", "7", "10"], banterHint: "La liste a raccourci en 2006, et elle est restée gentille." },
          de: { categoryTitle: "Heimat-System", prompt: "Wie viele Planeten hat unser Sonnensystem?", choices: ["8", "9", "7", "10"], banterHint: "Die Reihe wurde 2006 kürzer und blieb freundlich." },
        },
      }),
      q({
        id: "cq-e-alpha-banana",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-alpha",
        structure: "colour",
        fromStructure: "colour",
        humorous: true,
        funny: true,
        injection: "escalation",
        technique: "escalation",
        correctIndex: 0,
        jokeWrongs: {
          2: {
            en: "Brown, a day past the lunchbox",
            fr: "Brun, un jour après la boîte à lunch",
            "fr-CA": "Brun, un jour après la boîte à lunch",
            de: "Braun, einen Tag nach der Lunchbox",
          },
          3: {
            en: "Red, if it tried out for the apple bowl",
            fr: "Rouge, s'il a passé l'audition du bol de pommes",
            "fr-CA": "Rouge, s'il a passé l'audition du bol de pommes",
            de: "Rot, falls es für die Apfelschale vorgesprochen hat",
          },
        },
        sources: [{ label: "Encyclopaedia Britannica — banana" }, { label: "Royal Botanic Gardens, Kew — banana" }],
        text: {
          en: { categoryTitle: "Snack", prompt: "What colour is the peel of a ripe banana?", choices: ["Yellow", "Green", "Brown", "Red"], banterHint: "The story can grow. The peel stays the bright one." },
          fr: { categoryTitle: "Collation", prompt: "De quelle couleur est la peau d'une banane mûre ?", choices: ["Jaune", "Vert", "Brun", "Rouge"], banterHint: "L'histoire peut grossir. La peau reste la vive." },
          "fr-CA": { categoryTitle: "Collation", prompt: "C'est quoi la couleur de la peau d'une banane mûre ?", choices: ["Jaune", "Vert", "Brun", "Rouge"], banterHint: "L'histoire peut grossir. La peau reste la vive." },
          de: { categoryTitle: "Snack", prompt: "Welche Farbe hat die Schale einer reifen Banane?", choices: ["Gelb", "Grün", "Braun", "Rot"], banterHint: "Die Geschichte darf wachsen. Die Schale bleibt die helle." },
        },
      }),
      q({
        id: "cq-e-alpha-leap",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-alpha",
        correctIndex: 0,
        sources: [{ label: "US Naval Observatory — leap years" }, { label: "Encyclopaedia Britannica — calendar" }],
        text: {
          en: { categoryTitle: "Extra Day", prompt: "How many days are in a leap year?", choices: ["366", "365", "364", "360"], banterHint: "February borrows one day, then gives the year back." },
          fr: { categoryTitle: "Jour en plus", prompt: "Combien de jours compte une année bissextile ?", choices: ["366", "365", "364", "360"], banterHint: "Février emprunte un jour, puis rend l'année." },
          "fr-CA": { categoryTitle: "Jour en plus", prompt: "Une année bissextile a combien de jours ?", choices: ["366", "365", "364", "360"], banterHint: "Février emprunte une journée, puis rend l'année." },
          de: { categoryTitle: "Extra-Tag", prompt: "Wie viele Tage hat ein Schaltjahr?", choices: ["366", "365", "364", "360"], banterHint: "Der Februar leiht sich einen Tag und gibt das Jahr zurück." },
        },
      }),
      q({
        id: "cq-h-alpha-elephant",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-alpha",
        correctIndex: 0,
        sources: [{ label: "Encyclopaedia Britannica — African elephant" }, { label: "WWF — African elephant" }],
        text: {
          en: { categoryTitle: "On Land", prompt: "Which animal is the largest living land animal?", choices: ["African elephant", "Blue whale", "Giraffe", "Polar bear"], banterHint: "The whale takes the ocean. This one stays on the ground." },
          fr: { categoryTitle: "Sur terre", prompt: "Quel animal est le plus grand animal terrestre vivant ?", choices: ["L'éléphant d'Afrique", "La baleine bleue", "La girafe", "L'ours polaire"], banterHint: "La baleine prend l'océan. Celui-ci reste au sol." },
          "fr-CA": { categoryTitle: "Sur terre", prompt: "C'est quoi le plus grand animal terrestre vivant ?", choices: ["L'éléphant d'Afrique", "La baleine bleue", "La girafe", "L'ours polaire"], banterHint: "La baleine prend l'océan. Celui-ci reste au sol." },
          de: { categoryTitle: "An Land", prompt: "Welches Tier ist das größte lebende Landtier?", choices: ["Afrikanischer Elefant", "Blauwal", "Giraffe", "Eisbär"], banterHint: "Der Wal nimmt den Ozean. Dieses bleibt am Boden." },
        },
      }),
    ],
  },
  {
    bot: "Creator Multi-gen",
    generation: "multi-gen",
    questions: [
      q({
        id: "cq-e-multi-guitar",
        tier: "easy",
        topic: "music",
        generation: "multi-gen",
        correctIndex: 1,
        sources: [{ label: "Encyclopaedia Britannica — guitar" }, { label: "Metropolitan Museum — string instruments" }],
        text: {
          en: { categoryTitle: "Six Strings", prompt: "How many strings does a standard guitar have?", choices: ["Four", "Six", "Eight", "Twelve"], banterHint: "Twelve-string guitars are the extra-loud cousins." },
          fr: { categoryTitle: "Six cordes", prompt: "Combien de cordes a une guitare standard ?", choices: ["Quatre", "Six", "Huit", "Douze"], banterHint: "Les guitares à douze cordes sont les cousines plus bruyantes." },
          "fr-CA": { categoryTitle: "Six cordes", prompt: "Une guitare standard a combien de cordes ?", choices: ["Quatre", "Six", "Huit", "Douze"], banterHint: "Les guitares à douze cordes sont les cousines plus bruyantes." },
          de: { categoryTitle: "Sechs Saiten", prompt: "Wie viele Saiten hat eine gewöhnliche Gitarre?", choices: ["Vier", "Sechs", "Acht", "Zwölf"], banterHint: "Zwölfsaiter sind die lauteren Verwandten." },
        },
      }),
      q({
        id: "cq-e-multi-boil",
        tier: "easy",
        topic: "current-culture",
        generation: "multi-gen",
        correctIndex: 0,
        sources: [{ label: "NIST — water properties" }, { label: "Encyclopaedia Britannica — boiling point" }],
        text: {
          en: { categoryTitle: "Kettle", prompt: "What is the boiling point of water at sea level, in Celsius?", choices: ["100", "90", "80", "120"], banterHint: "Up a mountain, the kettle finishes a little sooner." },
          fr: { categoryTitle: "Bouilloire", prompt: "Quel est le point d'ébullition de l'eau au niveau de la mer, en Celsius ?", choices: ["100", "90", "80", "120"], banterHint: "En montagne, la bouilloire finit un peu plus tôt." },
          "fr-CA": { categoryTitle: "Bouilloire", prompt: "Le point d'ébullition de l'eau au niveau de la mer, en Celsius, c'est quoi ?", choices: ["100", "90", "80", "120"], banterHint: "En montagne, la bouilloire finit un peu plus tôt." },
          de: { categoryTitle: "Kessel", prompt: "Wie hoch ist der Siedepunkt von Wasser auf Meereshöhe, in Celsius?", choices: ["100", "90", "80", "120"], banterHint: "Auf dem Berg ist der Kessel etwas früher fertig." },
        },
      }),
      q({
        id: "cq-h-multi-photo",
        tier: "hard",
        topic: "current-culture",
        generation: "multi-gen",
        correctIndex: 2,
        sources: [{ label: "Encyclopaedia Britannica — photosynthesis" }, { label: "NASA Earth Observatory — carbon cycle" }],
        text: {
          en: { categoryTitle: "Green Work", prompt: "Which gas do plants take in during photosynthesis?", choices: ["Oxygen", "Nitrogen", "Carbon dioxide", "Helium"], banterHint: "They hand oxygen back to the room." },
          fr: { categoryTitle: "Travail vert", prompt: "Quel gaz les plantes absorbent-elles pendant la photosynthèse ?", choices: ["L'oxygène", "L'azote", "Le dioxyde de carbone", "L'hélium"], banterHint: "Elles rendent l'oxygène à la pièce." },
          "fr-CA": { categoryTitle: "Travail vert", prompt: "Quel gaz les plantes prennent pendant la photosynthèse ?", choices: ["L'oxygène", "L'azote", "Le dioxyde de carbone", "L'hélium"], banterHint: "Elles redonnent l'oxygène à la pièce." },
          de: { categoryTitle: "Grüne Arbeit", prompt: "Welches Gas nehmen Pflanzen bei der Fotosynthese auf?", choices: ["Sauerstoff", "Stickstoff", "Kohlenstoffdioxid", "Helium"], banterHint: "Sauerstoff geben sie dem Raum zurück." },
        },
      }),
      q({
        id: "cq-h-multi-pitch",
        tier: "hard",
        topic: "current-culture",
        generation: "multi-gen",
        correctIndex: 1,
        sources: [{ label: "FIFA — laws of the game" }, { label: "Encyclopaedia Britannica — football" }],
        text: {
          en: { categoryTitle: "On the Field", prompt: "How many players from one soccer team are on the field at a time?", choices: ["9", "11", "13", "15"], banterHint: "The goalkeeper counts as one of them." },
          fr: { categoryTitle: "Sur le terrain", prompt: "Combien de joueurs d'une équipe de football sont sur le terrain en même temps ?", choices: ["9", "11", "13", "15"], banterHint: "Le gardien compte parmi eux." },
          "fr-CA": { categoryTitle: "Sur le terrain", prompt: "Combien de joueurs d'une équipe de soccer sont sur le terrain en même temps ?", choices: ["9", "11", "13", "15"], banterHint: "Le gardien compte parmi eux." },
          de: { categoryTitle: "Auf dem Platz", prompt: "Wie viele Spieler einer Fußballmannschaft stehen gleichzeitig auf dem Feld?", choices: ["9", "11", "13", "15"], banterHint: "Der Torwart zählt mit." },
        },
      }),
      q({
        id: "cq-h-multi-compass",
        tier: "hard",
        topic: "current-culture",
        generation: "multi-gen",
        funny: true,
        technique: "misdirection",
        structure: "joke",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "True North", prompt: "Why did the compass join the quiz?", choices: ["It wanted to get its bearings", "It hid the map", "It lost the needle", "It skipped the trail"], banterHint: "North stayed a kind direction." },
          fr: { categoryTitle: "Plein nord", prompt: "Pourquoi la boussole a-t-elle rejoint le quiz ?", choices: ["Elle voulait trouver ses repères", "Elle a caché la carte", "Elle a perdu l'aiguille", "Elle a sauté le sentier"], banterHint: "Le nord est resté une direction gentille." },
          "fr-CA": { categoryTitle: "Plein nord", prompt: "Pourquoi la boussole s'est jointe au quiz ?", choices: ["Elle voulait trouver ses repères", "Elle a caché la carte", "Elle a perdu l'aiguille", "Elle a sauté le sentier"], banterHint: "Le nord est resté une direction gentille." },
          de: { categoryTitle: "Kurs Nord", prompt: "Warum trat der Kompass dem Quiz bei?", choices: ["Er wollte sich orientieren", "Er versteckte die Karte", "Er verlor die Nadel", "Er übersprang den Weg"], banterHint: "Norden blieb eine freundliche Richtung." },
        },
      }),
      q({
        id: "cq-h-multi-eclipse",
        tier: "hard",
        topic: "current-culture",
        generation: "multi-gen",
        structure: "colour",
        correctIndex: 0,
        sources: [{ label: "NASA — lunar eclipse" }, { label: "Encyclopaedia Britannica — eclipse" }],
        text: {
          en: { categoryTitle: "Night Shade", prompt: "What colour is the Moon during a total lunar eclipse?", choices: ["Red", "Blue", "Green", "White"], banterHint: "Earth's shadow lends that shade." },
          fr: { categoryTitle: "Teinte de nuit", prompt: "De quelle couleur est la Lune pendant une éclipse lunaire totale ?", choices: ["Rouge", "Bleu", "Vert", "Blanc"], banterHint: "L'ombre de la Terre prête cette teinte." },
          "fr-CA": { categoryTitle: "Teinte de nuit", prompt: "C'est quoi la couleur de la Lune pendant une éclipse lunaire totale ?", choices: ["Rouge", "Bleu", "Vert", "Blanc"], banterHint: "L'ombre de la Terre prête cette teinte." },
          de: { categoryTitle: "Nachtton", prompt: "Welche Farbe hat der Mond während einer totalen Mondfinsternis?", choices: ["Rot", "Blau", "Grün", "Weiß"], banterHint: "Der Schatten der Erde leiht diesen Ton." },
        },
      }),
      q({
        id: "cq-e-multi-titanic",
        tier: "easy",
        topic: "current-culture",
        generation: "multi-gen",
        structure: "when",
        fromStructure: "when",
        humorous: true,
        funny: true,
        injection: "dialogue",
        technique: "dialogue",
        correctIndex: 0,
        jokeWrongs: {
          2: {
            en: "May 7, whenever the sequel docks",
            fr: "7 mai, quand la suite accoste",
            "fr-CA": "7 mai, quand la suite accoste",
            de: "7. Mai, wenn die Fortsetzung anlegt",
          },
          3: {
            en: "April 1 (April Fool's Day)",
            fr: "1 avril (poisson d'avril)",
            "fr-CA": "1er avril (poisson d'avril)",
            de: "1. April (Aprilscherz)",
          },
        },
        sources: [{ label: "Encyclopaedia Britannica — Titanic" }, { label: "National Maritime Museum — Titanic" }],
        text: {
          en: { categoryTitle: "On the Walk", prompt: "When did the Titanic sink?", choices: ["April 15, 1912", "April 15, 1911", "May 7, 1915", "December 16, 1912"], banterHint: "The other person answered the question that was asked." },
          fr: { categoryTitle: "En marchant", prompt: "Quand le Titanic a-t-il coulé ?", choices: ["15 avril 1912", "15 avril 1911", "7 mai 1915", "16 décembre 1912"], banterHint: "L'autre a répondu à la question posée." },
          "fr-CA": { categoryTitle: "En marchant", prompt: "Le Titanic a coulé quand ?", choices: ["15 avril 1912", "15 avril 1911", "7 mai 1915", "16 décembre 1912"], banterHint: "L'autre a répondu à la question posée." },
          de: { categoryTitle: "Unterwegs", prompt: "Wann ist die Titanic gesunken?", choices: ["15. April 1912", "15. April 1911", "7. Mai 1915", "16. Dezember 1912"], banterHint: "Die andere Person hat die gestellte Frage beantwortet." },
        },
      }),
      q({
        id: "cq-h-multi-titanic-hull",
        tier: "hard",
        topic: "current-culture",
        generation: "multi-gen",
        structure: "colour",
        fromStructure: "when",
        humorous: true,
        funny: true,
        renegade: true,
        injection: "dialogue",
        technique: "dialogue",
        correctIndex: 0,
        jokeWrongs: {
          2: {
            en: "Red, if the funnel is telling the story",
            fr: "Rouge, si la cheminée raconte l'histoire",
            "fr-CA": "Rouge, si la cheminée raconte l'histoire",
            de: "Rot, wenn der Schornstein die Geschichte erzählt",
          },
          3: {
            en: "Green, after a long stay in the harbour",
            fr: "Vert, après un long séjour au port",
            "fr-CA": "Vert, après un long séjour au port",
            de: "Grün, nach einem langen Aufenthalt im Hafen",
          },
        },
        sources: [{ label: "Encyclopaedia Britannica — Titanic" }, { label: "National Maritime Museum — Titanic" }],
        text: {
          en: { categoryTitle: "Same Walk", prompt: "What colour was the hull of the Titanic?", choices: ["Black", "White", "Red", "Green"], banterHint: "Same walk. Different structure. The hull was not the date." },
          fr: { categoryTitle: "Même marche", prompt: "De quelle couleur était la coque du Titanic ?", choices: ["Noir", "Blanc", "Rouge", "Vert"], banterHint: "Même marche. Autre structure. La coque n'était pas la date." },
          "fr-CA": { categoryTitle: "Même marche", prompt: "C'est quoi la couleur de la coque du Titanic ?", choices: ["Noir", "Blanc", "Rouge", "Vert"], banterHint: "Même marche. Autre structure. La coque n'était pas la date." },
          de: { categoryTitle: "Gleicher Weg", prompt: "Welche Farbe hatte der Rumpf der Titanic?", choices: ["Schwarz", "Weiß", "Rot", "Grün"], banterHint: "Gleicher Weg. Andere Struktur. Der Rumpf war nicht das Datum." },
        },
      }),
      q({
        id: "cq-e-multi-stop",
        tier: "easy",
        topic: "current-culture",
        generation: "multi-gen",
        correctIndex: 0,
        sources: [{ label: "Federal Highway Administration — stop sign" }, { label: "Encyclopaedia Britannica — traffic sign" }],
        text: {
          en: { categoryTitle: "Octagon", prompt: "How many sides does a standard stop sign have?", choices: ["8", "6", "4", "10"], banterHint: "Count the flat edges, not the pole." },
          fr: { categoryTitle: "Octogone", prompt: "Combien de côtés a un panneau stop standard ?", choices: ["8", "6", "4", "10"], banterHint: "Compte les bords plats, pas le poteau." },
          "fr-CA": { categoryTitle: "Octogone", prompt: "Un panneau d'arrêt standard a combien de côtés ?", choices: ["8", "6", "4", "10"], banterHint: "Compte les bords plats, pas le poteau." },
          de: { categoryTitle: "Achteck", prompt: "Wie viele Seiten hat ein übliches Stoppschild?", choices: ["8", "6", "4", "10"], banterHint: "Zähl die flachen Kanten, nicht den Pfosten." },
        },
      }),
      q({
        id: "cq-e-multi-sky",
        tier: "easy",
        topic: "current-culture",
        generation: "multi-gen",
        structure: "colour",
        fromStructure: "colour",
        humorous: true,
        funny: true,
        injection: "aside",
        technique: "aside",
        correctIndex: 0,
        jokeWrongs: {
          1: {
            en: "Green, if the lawn got promoted",
            fr: "Vert, si la pelouse a eu une promotion",
            "fr-CA": "Vert, si la pelouse a eu une promotion",
            de: "Grün, falls der Rasen befördert wurde",
          },
          2: {
            en: "Red, saved for the sunset shift",
            fr: "Rouge, gardé pour l'équipe du coucher",
            "fr-CA": "Rouge, gardé pour l'équipe du coucher",
            de: "Rot, aufgehoben für die Abendschicht",
          },
        },
        sources: [{ label: "NASA — Earth's atmosphere" }, { label: "Encyclopaedia Britannica — sky" }],
        text: {
          en: { categoryTitle: "Overhead", prompt: "What colour is a clear daytime sky?", choices: ["Blue", "Green", "Red", "Black"], banterHint: "Step back in. The answer is the ordinary one." },
          fr: { categoryTitle: "Au-dessus", prompt: "De quelle couleur est un ciel clair en journée ?", choices: ["Bleu", "Vert", "Rouge", "Noir"], banterHint: "Reviens dans la scène. La réponse est la simple." },
          "fr-CA": { categoryTitle: "Au-dessus", prompt: "C'est quoi la couleur d'un ciel clair en journée ?", choices: ["Bleu", "Vert", "Rouge", "Noir"], banterHint: "Reviens dans la scène. La réponse est la simple." },
          de: { categoryTitle: "Über uns", prompt: "Welche Farbe hat ein klarer Himmel am Tag?", choices: ["Blau", "Grün", "Rot", "Schwarz"], banterHint: "Zurück in die Szene. Die Antwort ist die gewöhnliche." },
        },
      }),
      q({
        id: "cq-e-multi-pacific",
        tier: "easy",
        topic: "geography",
        generation: "multi-gen",
        correctIndex: 0,
        sources: [{ label: "NOAA — Pacific Ocean" }, { label: "Encyclopaedia Britannica — Pacific Ocean" }],
        text: {
          en: { categoryTitle: "Open Water", prompt: "Which ocean is the largest on Earth?", choices: ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"], banterHint: "The map gives it the widest blue." },
          fr: { categoryTitle: "Eau libre", prompt: "Quel océan est le plus grand sur Terre ?", choices: ["L'océan Pacifique", "L'océan Atlantique", "L'océan Indien", "L'océan Arctique"], banterHint: "La carte lui donne le bleu le plus large." },
          "fr-CA": { categoryTitle: "Eau libre", prompt: "C'est quoi le plus grand océan sur la Terre ?", choices: ["L'océan Pacifique", "L'océan Atlantique", "L'océan Indien", "L'océan Arctique"], banterHint: "La carte lui donne le bleu le plus large." },
          de: { categoryTitle: "Offenes Wasser", prompt: "Welcher Ozean ist der größte auf der Erde?", choices: ["Pazifischer Ozean", "Atlantischer Ozean", "Indischer Ozean", "Arktischer Ozean"], banterHint: "Die Karte gibt ihm das breiteste Blau." },
        },
      }),
      q({
        id: "cq-h-multi-piano",
        tier: "hard",
        topic: "music",
        generation: "multi-gen",
        correctIndex: 0,
        sources: [{ label: "Encyclopaedia Britannica — piano" }, { label: "Steinway & Sons — piano keyboard" }],
        text: {
          en: { categoryTitle: "Keyboard", prompt: "How many keys does a standard piano have?", choices: ["88", "76", "61", "92"], banterHint: "Count the black and the white. The total is the long one." },
          fr: { categoryTitle: "Clavier", prompt: "Combien de touches a un piano standard ?", choices: ["88", "76", "61", "92"], banterHint: "Compte les noires et les blanches. Le total est le long." },
          "fr-CA": { categoryTitle: "Clavier", prompt: "Un piano standard a combien de touches ?", choices: ["88", "76", "61", "92"], banterHint: "Compte les noires et les blanches. Le total est le long." },
          de: { categoryTitle: "Tastatur", prompt: "Wie viele Tasten hat ein gewöhnliches Klavier?", choices: ["88", "76", "61", "92"], banterHint: "Zähl die schwarzen und die weißen. Die Summe ist die lange." },
        },
      }),
    ],
  },
];

export function creatorQuestions(locale = "en") {
  const out = [];
  for (const creator of CREATORS) {
    for (const row of creator.questions) {
      const flat = translateQuestion(row, locale);
      if (flat) out.push(flat);
    }
  }
  return out;
}
