/**
 * One creator for each generation pack. They write original questions.
 * Some jokes are easy or hard for general play. Colour questions ask
 * "What colour is…". Gen Alpha jokes stay on easy or hard.
 */
import { translateQuestion } from "./translators.js";

const WEEK = "2026-W39";

function q(row) {
  return { addedWeek: WEEK, sources: row.sources || [], ...row };
}

export const CREATORS = [
  {
    bot: "Creator Silent",
    generation: "silent-generation",
    questions: [
      q({
        id: "cq-e-silent-roar",
        tier: "easy",
        topic: "current-culture",
        generation: "silent-generation",
        correctIndex: 0,
        sources: [{ label: "Library of Congress — American history" }, { label: "Encyclopaedia Britannica — 1920s" }],
        text: {
          en: { categoryTitle: "Jazz Decade", prompt: "What nickname is given to the 1920s in the United States?", choices: ["The Roaring Twenties", "The Gilded Age", "The Depression Years", "The Space Age"], banterHint: "The bands were loud. The name stuck." },
          fr: { categoryTitle: "Décennie jazz", prompt: "Quel surnom donne-t-on aux années 1920 aux États-Unis ?", choices: ["Les Années folles", "L'Âge doré", "Les années de crise", "L'ère spatiale"], banterHint: "Les orchestres jouaient fort. Le surnom est resté." },
          "fr-CA": { categoryTitle: "Décennie jazz", prompt: "Les années 1920 aux États-Unis portent quel surnom ?", choices: ["Les années folles", "L'âge d'or", "Les années de la Crise", "L'ère de l'espace"], banterHint: "Les orchestres jouaient fort. Le surnom est resté." },
          de: { categoryTitle: "Jazzjahrzehnt", prompt: "Welchen Spitznamen tragen die 1920er-Jahre in den USA?", choices: ["Die wilden Zwanziger", "Das vergoldete Zeitalter", "Die Depressionsjahre", "Das Raumfahrtzeitalter"], banterHint: "Die Bands waren laut. Der Name blieb." },
        },
      }),
      q({
        id: "cq-e-silent-vote",
        tier: "easy",
        topic: "current-culture",
        generation: "silent-generation",
        correctIndex: 0,
        sources: [{ label: "National Archives — 19th Amendment" }, { label: "Encyclopaedia Britannica — women's suffrage" }],
        text: {
          en: { categoryTitle: "Ballot Box", prompt: "Which U.S. constitutional amendment, ratified in 1920, recognized women's right to vote?", choices: ["The 19th Amendment", "The 15th Amendment", "The 13th Amendment", "The 26th Amendment"], banterHint: "The line at the poll got longer, on purpose." },
          fr: { categoryTitle: "Urne", prompt: "Quel amendement de la Constitution américaine, ratifié en 1920, a reconnu le droit de vote des femmes ?", choices: ["Le 19e amendement", "Le 15e amendement", "Le 13e amendement", "Le 26e amendement"], banterHint: "La file devant l'urne s'est allongée, exprès." },
          "fr-CA": { categoryTitle: "Urne", prompt: "Quel amendement de la Constitution des États-Unis, ratifié en 1920, reconnaît le droit de vote des femmes ?", choices: ["Le 19e amendement", "Le 15e amendement", "Le 13e amendement", "Le 26e amendement"], banterHint: "La file devant le bureau de vote a allongé, pour de bon." },
          de: { categoryTitle: "Wahlurne", prompt: "Welche Ergänzung der US-Verfassung von 1920 erkennt das Wahlrecht der Frauen an?", choices: ["Der 19. Zusatzartikel", "Der 15. Zusatzartikel", "Der 13. Zusatzartikel", "Der 26. Zusatzartikel"], banterHint: "Die Schlange vor dem Wahllokal wurde absichtlich länger." },
        },
      }),
      q({
        id: "cq-h-silent-chamberlain",
        tier: "hard",
        topic: "current-culture",
        generation: "silent-generation",
        correctIndex: 0,
        sources: [{ label: "UK National Archives — 1939" }, { label: "Encyclopaedia Britannica — Neville Chamberlain" }],
        text: {
          en: { categoryTitle: "September 1939", prompt: "Who was Prime Minister of the United Kingdom when Britain declared war on Germany in 1939?", choices: ["Neville Chamberlain", "Winston Churchill", "Clement Attlee", "Stanley Baldwin"], banterHint: "Churchill took the chair the next year." },
          fr: { categoryTitle: "Septembre 1939", prompt: "Qui était Premier ministre du Royaume-Uni lorsque la Grande-Bretagne a déclaré la guerre à l'Allemagne en 1939 ?", choices: ["Neville Chamberlain", "Winston Churchill", "Clement Attlee", "Stanley Baldwin"], banterHint: "Churchill a pris le fauteuil l'année suivante." },
          "fr-CA": { categoryTitle: "Septembre 1939", prompt: "Qui était le premier ministre du Royaume-Uni quand la Grande-Bretagne a déclaré la guerre à l'Allemagne en 1939 ?", choices: ["Neville Chamberlain", "Winston Churchill", "Clement Attlee", "Stanley Baldwin"], banterHint: "Churchill a pris la place l'année d'après." },
          de: { categoryTitle: "September 1939", prompt: "Wer war Premierminister des Vereinigten Königreichs, als Großbritannien 1939 Deutschland den Krieg erklärte?", choices: ["Neville Chamberlain", "Winston Churchill", "Clement Attlee", "Stanley Baldwin"], banterHint: "Churchill übernahm den Stuhl im Jahr darauf." },
        },
      }),
      q({
        id: "cq-h-silent-assembly",
        tier: "hard",
        topic: "current-culture",
        generation: "silent-generation",
        correctIndex: 0,
        sources: [{ label: "United Nations — General Assembly history" }, { label: "Encyclopaedia Britannica — United Nations" }],
        text: {
          en: { categoryTitle: "First Session", prompt: "In which city did the United Nations hold its first General Assembly in 1946?", choices: ["London", "New York", "Geneva", "Paris"], banterHint: "New York became home a few years later." },
          fr: { categoryTitle: "Première session", prompt: "Dans quelle ville l'ONU a-t-elle tenu sa première Assemblée générale en 1946 ?", choices: ["Londres", "New York", "Genève", "Paris"], banterHint: "New York est devenu le siège quelques années plus tard." },
          "fr-CA": { categoryTitle: "Première session", prompt: "Dans quelle ville l'ONU a tenu sa première Assemblée générale en 1946 ?", choices: ["Londres", "New York", "Genève", "Paris"], banterHint: "New York est devenu le siège quelques années plus tard." },
          de: { categoryTitle: "Erste Sitzung", prompt: "In welcher Stadt hielt die UNO 1946 ihre erste Generalversammlung ab?", choices: ["London", "New York", "Genf", "Paris"], banterHint: "New York wurde ein paar Jahre später der Sitz." },
        },
      }),
      q({
        id: "cq-e-silent-radio",
        tier: "easy",
        topic: "current-culture",
        generation: "silent-generation",
        funny: true,
        technique: "wordplay",
        structure: "joke",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "By the Window", prompt: "Why did the radio sit near the window?", choices: ["It wanted to catch a wave", "It hid from the news", "It lost the dial", "It preferred silence"], banterHint: "The song still came through." },
          fr: { categoryTitle: "Près de la fenêtre", prompt: "Pourquoi la radio s'est-elle assise près de la fenêtre ?", choices: ["Elle voulait capter une onde", "Elle se cachait des nouvelles", "Elle a perdu le cadran", "Elle préférait le silence"], banterHint: "La chanson passait quand même." },
          "fr-CA": { categoryTitle: "Près de la fenêtre", prompt: "Pourquoi la radio s'est assise près de la fenêtre ?", choices: ["Elle voulait capter une onde", "Elle se cachait des nouvelles", "Elle a perdu le cadran", "Elle préférait le silence"], banterHint: "La chanson passait quand même." },
          de: { categoryTitle: "Am Fenster", prompt: "Warum saß das Radio am Fenster?", choices: ["Es wollte eine Welle fangen", "Es versteckte sich vor den Nachrichten", "Es verlor die Skala", "Es wollte Stille"], banterHint: "Das Lied kam trotzdem durch." },
        },
      }),
      q({
        id: "cq-e-silent-liberty",
        tier: "easy",
        topic: "current-culture",
        generation: "silent-generation",
        structure: "colour",
        correctIndex: 0,
        sources: [{ label: "National Park Service — Statue of Liberty" }, { label: "Encyclopaedia Britannica — Statue of Liberty" }],
        text: {
          en: { categoryTitle: "Copper Coat", prompt: "What colour is the Statue of Liberty today?", choices: ["Green", "Grey", "Gold", "White"], banterHint: "The copper coat changed after years of weather." },
          fr: { categoryTitle: "Manteau de cuivre", prompt: "De quelle couleur est la Statue de la Liberté aujourd'hui ?", choices: ["Vert", "Gris", "Or", "Blanc"], banterHint: "Le cuivre a changé après des années de temps." },
          "fr-CA": { categoryTitle: "Manteau de cuivre", prompt: "C'est quoi la couleur de la Statue de la Liberté aujourd'hui ?", choices: ["Vert", "Gris", "Or", "Blanc"], banterHint: "Le cuivre a changé après des années de temps." },
          de: { categoryTitle: "Kupfermantel", prompt: "Welche Farbe hat die Freiheitsstatue heute?", choices: ["Grün", "Grau", "Gold", "Weiß"], banterHint: "Das Kupfer hat sich nach Jahren Wetter verändert." },
        },
      }),
    ],
  },
  {
    bot: "Creator Boomer",
    generation: "baby-boomer",
    questions: [
      q({
        id: "cq-e-boomer-gaye",
        tier: "easy",
        topic: "music",
        generation: "baby-boomer",
        correctIndex: 1,
        sources: [{ label: "Motown / album notes — What's Going On" }, { label: "Encyclopaedia Britannica — Marvin Gaye" }],
        text: {
          en: { categoryTitle: "Soul Hour", prompt: "Who released the album What's Going On in 1971?", choices: ["Stevie Wonder", "Marvin Gaye", "Otis Redding", "Sam Cooke"], banterHint: "The questions on that record still stand." },
          fr: { categoryTitle: "Heure soul", prompt: "Qui a sorti l'album What's Going On en 1971 ?", choices: ["Stevie Wonder", "Marvin Gaye", "Otis Redding", "Sam Cooke"], banterHint: "Les questions de ce disque tiennent encore." },
          "fr-CA": { categoryTitle: "Heure soul", prompt: "Qui a lancé l'album What's Going On en 1971 ?", choices: ["Stevie Wonder", "Marvin Gaye", "Otis Redding", "Sam Cooke"], banterHint: "Les questions de ce disque tiennent encore." },
          de: { categoryTitle: "Soul-Stunde", prompt: "Wer veröffentlichte 1971 das Album What's Going On?", choices: ["Stevie Wonder", "Marvin Gaye", "Otis Redding", "Sam Cooke"], banterHint: "Die Fragen auf der Platte gelten noch." },
        },
      }),
      q({
        id: "cq-e-boomer-skylab",
        tier: "easy",
        topic: "current-culture",
        generation: "baby-boomer",
        correctIndex: 2,
        sources: [{ label: "NASA — Skylab" }, { label: "Encyclopaedia Britannica — space stations" }],
        text: {
          en: { categoryTitle: "Workshop in Orbit", prompt: "What was the name of NASA's first space station, launched in 1973?", choices: ["Mir", "Salyut", "Skylab", "Freedom"], banterHint: "A workshop with a very long commute." },
          fr: { categoryTitle: "Atelier en orbite", prompt: "Comment s'appelait la première station spatiale de la NASA, lancée en 1973 ?", choices: ["Mir", "Saliout", "Skylab", "Freedom"], banterHint: "Un atelier avec un très long trajet." },
          "fr-CA": { categoryTitle: "Atelier en orbite", prompt: "Quel était le nom de la première station spatiale de la NASA, lancée en 1973 ?", choices: ["Mir", "Saliout", "Skylab", "Freedom"], banterHint: "Un atelier avec un très long trajet." },
          de: { categoryTitle: "Werkstatt im Orbit", prompt: "Wie hieß die erste Raumstation der NASA, gestartet 1973?", choices: ["Mir", "Saljut", "Skylab", "Freedom"], banterHint: "Eine Werkstatt mit sehr langem Arbeitsweg." },
        },
      }),
      q({
        id: "cq-h-boomer-sesame",
        tier: "hard",
        topic: "film-tv",
        generation: "baby-boomer",
        correctIndex: 0,
        sources: [{ label: "Sesame Workshop — history" }, { label: "Library of Congress — television history" }],
        text: {
          en: { categoryTitle: "Street Premiere", prompt: "In which year did Sesame Street first air in the United States?", choices: ["1969", "1965", "1974", "1979"], banterHint: "The street opened near the end of the sixties." },
          fr: { categoryTitle: "Première dans la rue", prompt: "En quelle année Sesame Street a-t-il été diffusé pour la première fois aux États-Unis ?", choices: ["1969", "1965", "1974", "1979"], banterHint: "La rue a ouvert vers la fin des années soixante." },
          "fr-CA": { categoryTitle: "Première dans la rue", prompt: "En quelle année Sesame Street a été diffusé pour la première fois aux États-Unis ?", choices: ["1969", "1965", "1974", "1979"], banterHint: "La rue a ouvert vers la fin des années soixante." },
          de: { categoryTitle: "Straßenpremiere", prompt: "In welchem Jahr lief Sesame Street zum ersten Mal in den USA?", choices: ["1969", "1965", "1974", "1979"], banterHint: "Die Straße öffnete gegen Ende der Sechziger." },
        },
      }),
      q({
        id: "cq-h-boomer-earthday",
        tier: "hard",
        topic: "current-culture",
        generation: "baby-boomer",
        correctIndex: 1,
        sources: [{ label: "Earth Day Network — history" }, { label: "U.S. EPA — Earth Day" }],
        text: {
          en: { categoryTitle: "First Green Day", prompt: "In which year was the first Earth Day held?", choices: ["1962", "1970", "1977", "1984"], banterHint: "The planet got a date on the calendar." },
          fr: { categoryTitle: "Premier jour vert", prompt: "En quelle année a eu lieu le premier Jour de la Terre ?", choices: ["1962", "1970", "1977", "1984"], banterHint: "La planète a eu une date au calendrier." },
          "fr-CA": { categoryTitle: "Premier jour vert", prompt: "En quelle année a eu lieu le premier Jour de la Terre ?", choices: ["1962", "1970", "1977", "1984"], banterHint: "La planète a eu une date au calendrier." },
          de: { categoryTitle: "Erster grüner Tag", prompt: "In welchem Jahr fand der erste Earth Day statt?", choices: ["1962", "1970", "1977", "1984"], banterHint: "Der Planet bekam ein Datum im Kalender." },
        },
      }),
      q({
        id: "cq-h-boomer-record",
        tier: "hard",
        topic: "current-culture",
        generation: "baby-boomer",
        funny: true,
        technique: "callback",
        structure: "joke",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "Spin Again", prompt: "Why did the record stay friends with the player?", choices: ["It kept coming back around", "It hid in the sleeve", "It skipped the chorus", "It lost the label"], banterHint: "The next song still got a turn." },
          fr: { categoryTitle: "Encore un tour", prompt: "Pourquoi le disque est-il resté ami avec le tourne-disque ?", choices: ["Il revenait toujours", "Il se cachait dans la pochette", "Il sautait le refrain", "Il a perdu l'étiquette"], banterHint: "La chanson suivante a eu son tour." },
          "fr-CA": { categoryTitle: "Encore un tour", prompt: "Pourquoi le disque est resté ami avec le tourne-disque ?", choices: ["Il revenait toujours", "Il se cachait dans la pochette", "Il sautait le refrain", "Il a perdu l'étiquette"], banterHint: "La chanson suivante a eu son tour." },
          de: { categoryTitle: "Noch eine Runde", prompt: "Warum blieb die Schallplatte mit dem Spieler befreundet?", choices: ["Sie kam immer wieder herum", "Sie versteckte sich in der Hülle", "Sie übersprang den Refrain", "Sie verlor das Etikett"], banterHint: "Das nächste Lied kam trotzdem dran." },
        },
      }),
      q({
        id: "cq-e-boomer-submarine",
        tier: "easy",
        topic: "current-culture",
        generation: "baby-boomer",
        structure: "colour",
        correctIndex: 0,
        sources: [{ label: "Encyclopaedia Britannica — the Beatles" }, { label: "Library of Congress — Yellow Submarine" }],
        text: {
          en: { categoryTitle: "Under the Sea", prompt: "What colour is the submarine in the Beatles song?", choices: ["Yellow", "Blue", "Red", "Green"], banterHint: "The title gives the paint job away." },
          fr: { categoryTitle: "Sous la mer", prompt: "De quelle couleur est le sous-marin dans la chanson des Beatles ?", choices: ["Jaune", "Bleu", "Rouge", "Vert"], banterHint: "Le titre donne déjà la peinture." },
          "fr-CA": { categoryTitle: "Sous la mer", prompt: "C'est quoi la couleur du sous-marin dans la chanson des Beatles ?", choices: ["Jaune", "Bleu", "Rouge", "Vert"], banterHint: "Le titre donne déjà la peinture." },
          de: { categoryTitle: "Unter dem Meer", prompt: "Welche Farbe hat das U-Boot im Beatles-Lied?", choices: ["Gelb", "Blau", "Rot", "Grün"], banterHint: "Der Titel verrät schon die Farbe." },
        },
      }),
    ],
  },
  {
    bot: "Creator Gen X",
    generation: "gen-x",
    questions: [
      q({
        id: "cq-e-genx-gameboy",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-x",
        correctIndex: 0,
        sources: [{ label: "Nintendo — Game Boy history" }, { label: "Encyclopaedia Britannica — video game consoles" }],
        text: {
          en: { categoryTitle: "Pocket Screen", prompt: "Which handheld console did Nintendo release in 1989?", choices: ["Game Boy", "Game Gear", "Lynx", "PSP"], banterHint: "Tetris rode along in a lot of pockets." },
          fr: { categoryTitle: "Écran de poche", prompt: "Quelle console portable Nintendo a-t-elle sortie en 1989 ?", choices: ["Game Boy", "Game Gear", "Lynx", "PSP"], banterHint: "Tetris a voyagé dans beaucoup de poches." },
          "fr-CA": { categoryTitle: "Écran de poche", prompt: "Quelle console portative Nintendo a sortie en 1989 ?", choices: ["Game Boy", "Game Gear", "Lynx", "PSP"], banterHint: "Tetris a voyagé dans bien des poches." },
          de: { categoryTitle: "Taschenbildschirm", prompt: "Welche Handheld-Konsole brachte Nintendo 1989 heraus?", choices: ["Game Boy", "Game Gear", "Lynx", "PSP"], banterHint: "Tetris reiste in vielen Taschen mit." },
        },
      }),
      q({
        id: "cq-e-genx-pdf",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-x",
        correctIndex: 2,
        sources: [{ label: "Adobe — PDF history" }, { label: "Encyclopaedia Britannica — document formats" }],
        text: {
          en: { categoryTitle: "Paperless Page", prompt: "What does PDF stand for?", choices: ["Public Data File", "Printed Document Form", "Portable Document Format", "Personal Disk Folder"], banterHint: "The page learned to travel." },
          fr: { categoryTitle: "Page sans papier", prompt: "Que signifie PDF ?", choices: ["Public Data File", "Printed Document Form", "Portable Document Format", "Personal Disk Folder"], banterHint: "La page a appris à voyager." },
          "fr-CA": { categoryTitle: "Page sans papier", prompt: "PDF veut dire quoi ?", choices: ["Public Data File", "Printed Document Form", "Portable Document Format", "Personal Disk Folder"], banterHint: "La page a appris à voyager." },
          de: { categoryTitle: "Seite ohne Papier", prompt: "Wofür steht PDF?", choices: ["Public Data File", "Printed Document Form", "Portable Document Format", "Personal Disk Folder"], banterHint: "Die Seite hat reisen gelernt." },
        },
      }),
      q({
        id: "cq-h-genx-ram",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-x",
        correctIndex: 1,
        sources: [{ label: "Computer History Museum — memory" }, { label: "Encyclopaedia Britannica — computer memory" }],
        text: {
          en: { categoryTitle: "Short Memory", prompt: "What does RAM stand for in a computer?", choices: ["Read And Modify", "Random Access Memory", "Rapid Archive Module", "Remote Access Mainframe"], banterHint: "Fast memory, and it forgets when the power goes." },
          fr: { categoryTitle: "Mémoire courte", prompt: "Que signifie RAM dans un ordinateur ?", choices: ["Read And Modify", "Random Access Memory", "Rapid Archive Module", "Remote Access Mainframe"], banterHint: "Une mémoire rapide, qui oublie quand le courant coupe." },
          "fr-CA": { categoryTitle: "Mémoire courte", prompt: "RAM, dans un ordinateur, ça veut dire quoi ?", choices: ["Read And Modify", "Random Access Memory", "Rapid Archive Module", "Remote Access Mainframe"], banterHint: "Une mémoire rapide, qui oublie quand le courant coupe." },
          de: { categoryTitle: "Kurzes Gedächtnis", prompt: "Wofür steht RAM in einem Computer?", choices: ["Read And Modify", "Random Access Memory", "Rapid Archive Module", "Remote Access Mainframe"], banterHint: "Schneller Speicher, und er vergisst ohne Strom." },
        },
      }),
      q({
        id: "cq-h-genx-cd",
        tier: "hard",
        topic: "music",
        generation: "gen-x",
        correctIndex: 0,
        sources: [{ label: "Philips / Sony — Compact Disc" }, { label: "Encyclopaedia Britannica — compact disc" }],
        text: {
          en: { categoryTitle: "Silver Circle", prompt: "What does CD stand for in the music format introduced in the early 1980s?", choices: ["Compact Disc", "Cassette Deck", "Crystal Drive", "Catalog Download"], banterHint: "A small mirror that held an album." },
          fr: { categoryTitle: "Cercle d'argent", prompt: "Que signifie CD dans le format musical lancé au début des années 1980 ?", choices: ["Compact Disc", "Cassette Deck", "Crystal Drive", "Catalog Download"], banterHint: "Un petit miroir qui tenait un album." },
          "fr-CA": { categoryTitle: "Cercle d'argent", prompt: "CD, pour le format musical du début des années 1980, veut dire quoi ?", choices: ["Compact Disc", "Cassette Deck", "Crystal Drive", "Catalog Download"], banterHint: "Un petit miroir qui contenait un album." },
          de: { categoryTitle: "Silberner Kreis", prompt: "Wofür steht CD beim Musikformat der frühen 1980er?", choices: ["Compact Disc", "Cassette Deck", "Crystal Drive", "Catalog Download"], banterHint: "Ein kleiner Spiegel, der ein Album hielt." },
        },
      }),
      q({
        id: "cq-e-genx-cassette",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-x",
        funny: true,
        technique: "wordplay",
        structure: "joke",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "Wound Up", prompt: "Why did the cassette feel shy?", choices: ["It was a little wound up", "It lost the pencil", "It hid in the walkman", "It skipped the chorus"], banterHint: "Side B still got a listen." },
          fr: { categoryTitle: "Un peu tendue", prompt: "Pourquoi la cassette se sentait-elle timide ?", choices: ["Elle était un peu tendue", "Elle a perdu le crayon", "Elle s'est cachée dans le baladeur", "Elle a sauté le refrain"], banterHint: "La face B a quand même eu son écoute." },
          "fr-CA": { categoryTitle: "Un peu tendue", prompt: "Pourquoi la cassette se sentait gênée ?", choices: ["Elle était un peu tendue", "Elle a perdu le crayon", "Elle s'est cachée dans le baladeur", "Elle a sauté le refrain"], banterHint: "La face B a quand même eu son écoute." },
          de: { categoryTitle: "Aufgedreht", prompt: "Warum war die Kassette schüchtern?", choices: ["Sie war etwas aufgedreht", "Sie verlor den Bleistift", "Sie versteckte sich im Walkman", "Sie übersprang den Refrain"], banterHint: "Seite B wurde trotzdem gehört." },
        },
      }),
      q({
        id: "cq-h-genx-blinky",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-x",
        structure: "colour",
        correctIndex: 0,
        sources: [{ label: "Bandai Namco — Pac-Man" }, { label: "Encyclopaedia Britannica — Pac-Man" }],
        text: {
          en: { categoryTitle: "Ghost Duty", prompt: "What colour is Blinky, the Pac-Man ghost?", choices: ["Red", "Pink", "Cyan", "Orange"], banterHint: "The other three ghosts wear the rest." },
          fr: { categoryTitle: "Service fantôme", prompt: "De quelle couleur est Blinky, le fantôme de Pac-Man ?", choices: ["Rouge", "Rose", "Cyan", "Orange"], banterHint: "Les trois autres portent le reste." },
          "fr-CA": { categoryTitle: "Service fantôme", prompt: "C'est quoi la couleur de Blinky, le fantôme de Pac-Man ?", choices: ["Rouge", "Rose", "Cyan", "Orange"], banterHint: "Les trois autres portent le reste." },
          de: { categoryTitle: "Geisterdienst", prompt: "Welche Farbe hat Blinky, der Pac-Man-Geist?", choices: ["Rot", "Rosa", "Cyan", "Orange"], banterHint: "Die anderen drei tragen den Rest." },
        },
      }),
    ],
  },
  {
    bot: "Creator Gen Y",
    generation: "gen-y",
    questions: [
      q({
        id: "cq-e-geny-wiki",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-y",
        correctIndex: 0,
        sources: [{ label: "Wikimedia Foundation — Wikipedia history" }, { label: "Encyclopaedia Britannica — Wikipedia" }],
        text: {
          en: { categoryTitle: "Open Book", prompt: "Which website, launched in 2001, lets people write encyclopedia articles together?", choices: ["Wikipedia", "MySpace", "GeoCities", "AltaVista"], banterHint: "The edit button is the whole idea." },
          fr: { categoryTitle: "Livre ouvert", prompt: "Quel site, lancé en 2001, permet d'écrire des articles d'encyclopédie à plusieurs ?", choices: ["Wikipédia", "MySpace", "GeoCities", "AltaVista"], banterHint: "Le bouton modifier est toute l'idée." },
          "fr-CA": { categoryTitle: "Livre ouvert", prompt: "Quel site, lancé en 2001, permet d'écrire des articles d'encyclopédie ensemble ?", choices: ["Wikipédia", "MySpace", "GeoCities", "AltaVista"], banterHint: "Le bouton modifier, c'est toute l'idée." },
          de: { categoryTitle: "Offenes Buch", prompt: "Welche Website, gestartet 2001, lässt Menschen Enzyklopädie-Artikel gemeinsam schreiben?", choices: ["Wikipedia", "MySpace", "GeoCities", "AltaVista"], banterHint: "Der Bearbeiten-Knopf ist die ganze Idee." },
        },
      }),
      q({
        id: "cq-e-geny-sms",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-y",
        correctIndex: 1,
        sources: [{ label: "GSM Association — SMS" }, { label: "Encyclopaedia Britannica — text messaging" }],
        text: {
          en: { categoryTitle: "Short Note", prompt: "What does SMS stand for?", choices: ["Simple Mail Switch", "Short Message Service", "Secure Media Stream", "Standard Mobile Signal"], banterHint: "One hundred and sixty characters, and a lot of plans." },
          fr: { categoryTitle: "Note courte", prompt: "Que signifie SMS ?", choices: ["Simple Mail Switch", "Short Message Service", "Secure Media Stream", "Standard Mobile Signal"], banterHint: "Cent soixante caractères, et beaucoup de rendez-vous." },
          "fr-CA": { categoryTitle: "Note courte", prompt: "SMS veut dire quoi ?", choices: ["Simple Mail Switch", "Short Message Service", "Secure Media Stream", "Standard Mobile Signal"], banterHint: "Cent soixante caractères, et beaucoup de rendez-vous." },
          de: { categoryTitle: "Kurze Notiz", prompt: "Wofür steht SMS?", choices: ["Simple Mail Switch", "Short Message Service", "Secure Media Stream", "Standard Mobile Signal"], banterHint: "Einhundertsechzig Zeichen, und viele Verabredungen." },
        },
      }),
      q({
        id: "cq-h-geny-iphone",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-y",
        correctIndex: 0,
        sources: [{ label: "Apple — iPhone announcement, 2007" }, { label: "Encyclopaedia Britannica — smartphone" }],
        text: {
          en: { categoryTitle: "Pocket Computer", prompt: "Which company released the first iPhone in 2007?", choices: ["Apple", "Nokia", "BlackBerry", "Motorola"], banterHint: "The keyboard moved onto the glass." },
          fr: { categoryTitle: "Ordinateur de poche", prompt: "Quelle société a sorti le premier iPhone en 2007 ?", choices: ["Apple", "Nokia", "BlackBerry", "Motorola"], banterHint: "Le clavier est passé sur la vitre." },
          "fr-CA": { categoryTitle: "Ordinateur de poche", prompt: "Quelle compagnie a lancé le premier iPhone en 2007 ?", choices: ["Apple", "Nokia", "BlackBerry", "Motorola"], banterHint: "Le clavier est passé sur la vitre." },
          de: { categoryTitle: "Taschengerät", prompt: "Welche Firma brachte 2007 das erste iPhone heraus?", choices: ["Apple", "Nokia", "BlackBerry", "Motorola"], banterHint: "Die Tastatur wanderte aufs Glas." },
        },
      }),
      q({
        id: "cq-h-geny-facebook",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-y",
        correctIndex: 2,
        sources: [{ label: "Meta — company history" }, { label: "Encyclopaedia Britannica — Facebook" }],
        text: {
          en: { categoryTitle: "Open Registration", prompt: "In which year did Facebook open registration beyond schools to anyone 13 or older?", choices: ["2004", "2005", "2006", "2008"], banterHint: "The campus gate came down in September." },
          fr: { categoryTitle: "Inscription ouverte", prompt: "En quelle année Facebook a-t-il ouvert l'inscription au-delà des écoles, à toute personne de 13 ans ou plus ?", choices: ["2004", "2005", "2006", "2008"], banterHint: "La porte du campus est tombée en septembre." },
          "fr-CA": { categoryTitle: "Inscription ouverte", prompt: "En quelle année Facebook a ouvert l'inscription au-delà des écoles, à toute personne de 13 ans ou plus ?", choices: ["2004", "2005", "2006", "2008"], banterHint: "La porte du campus est tombée en septembre." },
          de: { categoryTitle: "Offene Anmeldung", prompt: "In welchem Jahr öffnete Facebook die Anmeldung über Schulen hinaus für alle ab 13?", choices: ["2004", "2005", "2006", "2008"], banterHint: "Das Campus-Tor fiel im September." },
        },
      }),
      q({
        id: "cq-h-geny-inbox",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-y",
        funny: true,
        technique: "wordplay",
        structure: "joke",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "Still Calm", prompt: "Why did the inbox stay calm?", choices: ["It knew how to keep its letters", "It deleted the morning", "It hid the password", "It missed the send button"], banterHint: "The unread pile stayed polite." },
          fr: { categoryTitle: "Toujours calme", prompt: "Pourquoi la boîte de réception est-elle restée calme ?", choices: ["Elle savait garder ses lettres", "Elle a effacé le matin", "Elle a caché le mot de passe", "Elle a raté le bouton envoyer"], banterHint: "La pile non lue est restée polie." },
          "fr-CA": { categoryTitle: "Toujours calme", prompt: "Pourquoi la boîte de réception est restée calme ?", choices: ["Elle savait garder ses lettres", "Elle a effacé le matin", "Elle a caché le mot de passe", "Elle a raté le bouton envoyer"], banterHint: "La pile non lue est restée polie." },
          de: { categoryTitle: "Immer ruhig", prompt: "Warum blieb der Posteingang ruhig?", choices: ["Er wusste, wie man Briefe behält", "Er löschte den Morgen", "Er versteckte das Passwort", "Er verpasste den Senden-Knopf"], banterHint: "Der ungelesene Stapel blieb höflich." },
        },
      }),
      q({
        id: "cq-h-geny-ocean",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-y",
        structure: "colour",
        correctIndex: 0,
        sources: [{ label: "Paramount — Titanic (1997)" }, { label: "Encyclopaedia Britannica — Titanic, film" }],
        text: {
          en: { categoryTitle: "Jewel Case", prompt: "What colour is the Heart of the Ocean in the film Titanic?", choices: ["Blue", "Green", "Red", "Yellow"], banterHint: "The necklace kept that one shade." },
          fr: { categoryTitle: "Écrin", prompt: "De quelle couleur est le Cœur de l'océan dans le film Titanic ?", choices: ["Bleu", "Vert", "Rouge", "Jaune"], banterHint: "Le collier a gardé cette seule teinte." },
          "fr-CA": { categoryTitle: "Écrin", prompt: "C'est quoi la couleur du Cœur de l'océan dans le film Titanic ?", choices: ["Bleu", "Vert", "Rouge", "Jaune"], banterHint: "Le collier a gardé cette seule teinte." },
          de: { categoryTitle: "Schmucketui", prompt: "Welche Farbe hat das Herz des Ozeans im Film Titanic?", choices: ["Blau", "Grün", "Rot", "Gelb"], banterHint: "Die Kette behielt genau diesen Ton." },
        },
      }),
    ],
  },
  {
    bot: "Creator Gen Z",
    generation: "gen-z",
    questions: [
      q({
        id: "cq-e-genz-gif",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-z",
        correctIndex: 0,
        sources: [{ label: "CompuServe — GIF specification" }, { label: "Encyclopaedia Britannica — GIF" }],
        text: {
          en: { categoryTitle: "Tiny Loop", prompt: "What does GIF stand for?", choices: ["Graphics Interchange Format", "Global Image File", "Grouped Internet Frame", "General Icon Folder"], banterHint: "A picture that refuses to sit still." },
          fr: { categoryTitle: "Petite boucle", prompt: "Que signifie GIF ?", choices: ["Graphics Interchange Format", "Global Image File", "Grouped Internet Frame", "General Icon Folder"], banterHint: "Une image qui refuse de rester sage." },
          "fr-CA": { categoryTitle: "Petite boucle", prompt: "GIF veut dire quoi ?", choices: ["Graphics Interchange Format", "Global Image File", "Grouped Internet Frame", "General Icon Folder"], banterHint: "Une image qui refuse de rester tranquille." },
          de: { categoryTitle: "Kleine Schleife", prompt: "Wofür steht GIF?", choices: ["Graphics Interchange Format", "Global Image File", "Grouped Internet Frame", "General Icon Folder"], banterHint: "Ein Bild, das nicht stillsitzen will." },
        },
      }),
      q({
        id: "cq-e-genz-vr",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-z",
        correctIndex: 1,
        sources: [{ label: "IEEE — virtual reality overview" }, { label: "Encyclopaedia Britannica — virtual reality" }],
        text: {
          en: { categoryTitle: "Headset", prompt: "What does VR stand for in a headset?", choices: ["Video Relay", "Virtual Reality", "Visual Radio", "Vector Render"], banterHint: "The room stays put. The view does not." },
          fr: { categoryTitle: "Casque", prompt: "Que signifie VR sur un casque ?", choices: ["Video Relay", "Virtual Reality", "Visual Radio", "Vector Render"], banterHint: "La pièce reste là. La vue, non." },
          "fr-CA": { categoryTitle: "Casque", prompt: "VR, sur un casque, veut dire quoi ?", choices: ["Video Relay", "Virtual Reality", "Visual Radio", "Vector Render"], banterHint: "La pièce reste là. Pas la vue." },
          de: { categoryTitle: "Kopfhörerbrille", prompt: "Wofür steht VR bei einem Headset?", choices: ["Video Relay", "Virtual Reality", "Visual Radio", "Vector Render"], banterHint: "Der Raum bleibt. Die Sicht nicht." },
        },
      }),
      q({
        id: "cq-h-genz-bytedance",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-z",
        correctIndex: 2,
        sources: [{ label: "ByteDance — company overview" }, { label: "Encyclopaedia Britannica — TikTok" }],
        text: {
          en: { categoryTitle: "Short Video", prompt: "Which company owns TikTok?", choices: ["Meta", "Google", "ByteDance", "Snap"], banterHint: "The app is the famous part. The company is quieter." },
          fr: { categoryTitle: "Vidéo courte", prompt: "Quelle société possède TikTok ?", choices: ["Meta", "Google", "ByteDance", "Snap"], banterHint: "L'appli est la partie célèbre. La société, moins." },
          "fr-CA": { categoryTitle: "Vidéo courte", prompt: "Quelle compagnie possède TikTok ?", choices: ["Meta", "Google", "ByteDance", "Snap"], banterHint: "L'appli est la partie connue. La compagnie, moins." },
          de: { categoryTitle: "Kurzvideo", prompt: "Welche Firma besitzt TikTok?", choices: ["Meta", "Google", "ByteDance", "Snap"], banterHint: "Die App ist der berühmte Teil. Die Firma ist leiser." },
        },
      }),
      q({
        id: "cq-h-genz-hashtag",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-z",
        correctIndex: 0,
        sources: [{ label: "Oxford English Dictionary — hashtag" }, { label: "Encyclopaedia Britannica — social media" }],
        text: {
          en: { categoryTitle: "Pound Sign", prompt: "What is the name of the # symbol when it groups posts on social media?", choices: ["A hashtag", "An asterisk", "A caret", "A tilde"], banterHint: "One mark, and the posts find each other." },
          fr: { categoryTitle: "Dièse", prompt: "Comment appelle-t-on le symbole # quand il regroupe des posts sur les réseaux sociaux ?", choices: ["Un hashtag", "Un astérisque", "Un caret", "Un tilde"], banterHint: "Une marque, et les posts se retrouvent." },
          "fr-CA": { categoryTitle: "Dièse", prompt: "Comment on appelle le symbole # quand il regroupe des publications sur les réseaux sociaux ?", choices: ["Un hashtag", "Un astérisque", "Un caret", "Un tilde"], banterHint: "Une marque, et les publications se retrouvent." },
          de: { categoryTitle: "Raute", prompt: "Wie heißt das Zeichen #, wenn es Beiträge in sozialen Medien bündelt?", choices: ["Ein Hashtag", "Ein Sternchen", "Ein Caret", "Eine Tilde"], banterHint: "Ein Zeichen, und die Beiträge finden sich." },
        },
      }),
      q({
        id: "cq-e-genz-emoji",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-z",
        funny: true,
        technique: "misdirection",
        structure: "joke",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "One Eye", prompt: "Why did the emoji wink?", choices: ["It had a point to make", "It lost the other eye", "It hid the keyboard", "It missed the chat"], banterHint: "The message still landed kindly." },
          fr: { categoryTitle: "Un œil", prompt: "Pourquoi l'emoji a-t-il fait un clin d'œil ?", choices: ["Il avait quelque chose à dire", "Il a perdu l'autre œil", "Il a caché le clavier", "Il a raté la discussion"], banterHint: "Le message est quand même arrivé gentiment." },
          "fr-CA": { categoryTitle: "Un œil", prompt: "Pourquoi l'emoji a fait un clin d'œil ?", choices: ["Il avait quelque chose à dire", "Il a perdu l'autre œil", "Il a caché le clavier", "Il a manqué la discussion"], banterHint: "Le message est quand même arrivé gentiment." },
          de: { categoryTitle: "Ein Auge", prompt: "Warum zwinkerte das Emoji?", choices: ["Es hatte etwas zu sagen", "Es verlor das andere Auge", "Es versteckte die Tastatur", "Es verpasste den Chat"], banterHint: "Die Nachricht kam trotzdem freundlich an." },
        },
      }),
      q({
        id: "cq-e-genz-spotify",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-z",
        structure: "colour",
        correctIndex: 0,
        sources: [{ label: "Spotify — brand" }, { label: "Spotify Newsroom — company" }],
        text: {
          en: { categoryTitle: "Logo Circle", prompt: "What colour is the circle in the Spotify logo?", choices: ["Green", "Blue", "Red", "Yellow"], banterHint: "The sound waves sit on top of it." },
          fr: { categoryTitle: "Cercle du logo", prompt: "De quelle couleur est le cercle du logo Spotify ?", choices: ["Vert", "Bleu", "Rouge", "Jaune"], banterHint: "Les ondes sonores sont posées dessus." },
          "fr-CA": { categoryTitle: "Cercle du logo", prompt: "C'est quoi la couleur du cercle dans le logo Spotify ?", choices: ["Vert", "Bleu", "Rouge", "Jaune"], banterHint: "Les ondes sonores sont posées dessus." },
          de: { categoryTitle: "Logo-Kreis", prompt: "Welche Farbe hat der Kreis im Spotify-Logo?", choices: ["Grün", "Blau", "Rot", "Gelb"], banterHint: "Die Schallwellen liegen darauf." },
        },
      }),
    ],
  },
  {
    bot: "Creator Gen Alpha",
    generation: "gen-alpha",
    questions: [
      q({
        id: "cq-e-alpha-cat",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-alpha",
        funny: true,
        technique: "wordplay",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "Quiz Host", prompt: "What do you call a cat who hosts the quiz?", choices: ["The purr-son in charge", "A scaredy cat", "A copycat", "A catnap"], banterHint: "It still lands on its feet." },
          fr: { categoryTitle: "Hôte du quiz", prompt: "Comment appelle-t-on un chat qui présente le quiz ?", choices: ["Le ron-ron en chef", "Un chat peureux", "Un copieur", "Une sieste de chat"], banterHint: "Il retombe quand même sur ses pattes." },
          "fr-CA": { categoryTitle: "Animateur du quiz", prompt: "Comment on appelle un chat qui anime le quiz ?", choices: ["Le ronron en charge", "Un chat peureux", "Un copieur", "Un somme de chat"], banterHint: "Il retombe quand même sur ses pattes." },
          de: { categoryTitle: "Quiz-Katze", prompt: "Wie nennt man eine Katze, die das Quiz moderiert?", choices: ["Die Schnurr-Chefin", "Eine Angsthase", "Ein Nachmacher", "Ein Nickerchen"], banterHint: "Sie landet trotzdem auf den Pfoten." },
        },
      }),
      q({
        id: "cq-e-alpha-backpack",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-alpha",
        funny: true,
        technique: "misdirection",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "Good Day", prompt: "Why did the backpack look proud?", choices: ["It was carrying a good day", "It ate the homework", "It missed the bus", "It hid the map"], banterHint: "Every book got a lift." },
          fr: { categoryTitle: "Belle journée", prompt: "Pourquoi le sac à dos avait-il l'air fier ?", choices: ["Il portait une bonne journée", "Il a mangé les devoirs", "Il a raté le bus", "Il a caché la carte"], banterHint: "Chaque livre a eu un coup de main." },
          "fr-CA": { categoryTitle: "Belle journée", prompt: "Pourquoi le sac à dos avait l'air fier ?", choices: ["Il portait une bonne journée", "Il a mangé les devoirs", "Il a manqué l'autobus", "Il a caché la carte"], banterHint: "Chaque livre a eu un coup de pouce." },
          de: { categoryTitle: "Guter Tag", prompt: "Warum sah der Rucksack stolz aus?", choices: ["Er trug einen guten Tag", "Er aß die Hausaufgaben", "Er verpasste den Bus", "Er versteckte die Karte"], banterHint: "Jedes Buch bekam eine Mitfahrgelegenheit." },
        },
      }),
      q({
        id: "cq-h-alpha-pencil",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-alpha",
        funny: true,
        technique: "wordplay",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "Team Player", prompt: "Why did the pencil join the team?", choices: ["It could draw a crowd", "It rolled away", "It hid in the case", "It lost its cap"], banterHint: "The eraser had its back." },
          fr: { categoryTitle: "Esprit d'équipe", prompt: "Pourquoi le crayon a-t-il rejoint l'équipe ?", choices: ["Il savait attirer la foule", "Il a roulé plus loin", "Il s'est caché dans la trousse", "Il a perdu son capuchon"], banterHint: "La gomme veillait sur lui." },
          "fr-CA": { categoryTitle: "Esprit d'équipe", prompt: "Pourquoi le crayon s'est joint à l'équipe ?", choices: ["Il savait attirer la gang", "Il a roulé plus loin", "Il s'est caché dans l'étui", "Il a perdu son capuchon"], banterHint: "L'efface veillait sur lui." },
          de: { categoryTitle: "Mannschaft", prompt: "Warum trat der Bleistift der Mannschaft bei?", choices: ["Er konnte ein Publikum anziehen", "Er rollte weg", "Er versteckte sich im Etui", "Er verlor seine Kappe"], banterHint: "Der Radiergummi hielt ihm den Rücken frei." },
        },
      }),
      q({
        id: "cq-h-alpha-bookmark",
        tier: "hard",
        topic: "current-culture",
        generation: "gen-alpha",
        funny: true,
        technique: "callback",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "Still Here", prompt: "Why did the bookmark stay calm in the story?", choices: ["It always held its place", "It tore the page", "It skipped the ending", "It hid the title"], banterHint: "Chapter after chapter, still kind." },
          fr: { categoryTitle: "Toujours là", prompt: "Pourquoi le marque-page restait-il calme dans l'histoire ?", choices: ["Il gardait toujours sa place", "Il a déchiré la page", "Il a sauté la fin", "Il a caché le titre"], banterHint: "Chapitre après chapitre, toujours gentil." },
          "fr-CA": { categoryTitle: "Toujours là", prompt: "Pourquoi le signet restait calme dans l'histoire ?", choices: ["Il gardait toujours sa place", "Il a déchiré la page", "Il a sauté la fin", "Il a caché le titre"], banterHint: "Chapitre après chapitre, toujours gentil." },
          de: { categoryTitle: "Immer noch da", prompt: "Warum blieb das Lesezeichen in der Geschichte ruhig?", choices: ["Es behielt immer seinen Platz", "Es zerriss die Seite", "Es übersprang das Ende", "Es versteckte den Titel"], banterHint: "Kapitel für Kapitel, immer freundlich." },
        },
      }),
      q({
        id: "cq-e-alpha-frog",
        tier: "easy",
        topic: "current-culture",
        generation: "gen-alpha",
        funny: true,
        technique: "misdirection",
        structure: "colour",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "Open Mic", prompt: "What colour is a frog on open-mic night?", choices: ["Green", "Purple", "Orange", "Silver"], banterHint: "The room stayed ribbiting." },
          fr: { categoryTitle: "Scène ouverte", prompt: "De quelle couleur est une grenouille le soir du micro ouvert ?", choices: ["Vert", "Violet", "Orange", "Argent"], banterHint: "La salle est restée croassante." },
          "fr-CA": { categoryTitle: "Scène ouverte", prompt: "C'est quoi la couleur d'une grenouille le soir du micro ouvert ?", choices: ["Vert", "Violet", "Orange", "Argent"], banterHint: "La salle est restée croassante." },
          de: { categoryTitle: "Offenes Mikro", prompt: "Welche Farbe hat ein Frosch am Open-Mic-Abend?", choices: ["Grün", "Lila", "Orange", "Silber"], banterHint: "Der Raum blieb quakend freundlich." },
        },
      }),
    ],
  },
  {
    bot: "Creator Multi-gen",
    generation: "multi-gen",
    questions: [
      q({
        id: "cq-e-multi-guitar",
        tier: "easy",
        topic: "music",
        generation: "multi-gen",
        correctIndex: 1,
        sources: [{ label: "Encyclopaedia Britannica — guitar" }, { label: "Metropolitan Museum — string instruments" }],
        text: {
          en: { categoryTitle: "Six Strings", prompt: "How many strings does a standard guitar have?", choices: ["Four", "Six", "Eight", "Twelve"], banterHint: "Twelve-string guitars are the extra-loud cousins." },
          fr: { categoryTitle: "Six cordes", prompt: "Combien de cordes a une guitare standard ?", choices: ["Quatre", "Six", "Huit", "Douze"], banterHint: "Les guitares à douze cordes sont les cousines plus bruyantes." },
          "fr-CA": { categoryTitle: "Six cordes", prompt: "Une guitare standard a combien de cordes ?", choices: ["Quatre", "Six", "Huit", "Douze"], banterHint: "Les guitares à douze cordes sont les cousines plus bruyantes." },
          de: { categoryTitle: "Sechs Saiten", prompt: "Wie viele Saiten hat eine gewöhnliche Gitarre?", choices: ["Vier", "Sechs", "Acht", "Zwölf"], banterHint: "Zwölfsaiter sind die lauteren Verwandten." },
        },
      }),
      q({
        id: "cq-e-multi-boil",
        tier: "easy",
        topic: "current-culture",
        generation: "multi-gen",
        correctIndex: 0,
        sources: [{ label: "NIST — water properties" }, { label: "Encyclopaedia Britannica — boiling point" }],
        text: {
          en: { categoryTitle: "Kettle", prompt: "What is the boiling point of water at sea level, in Celsius?", choices: ["100", "90", "80", "120"], banterHint: "Up a mountain, the kettle finishes a little sooner." },
          fr: { categoryTitle: "Bouilloire", prompt: "Quel est le point d'ébullition de l'eau au niveau de la mer, en Celsius ?", choices: ["100", "90", "80", "120"], banterHint: "En montagne, la bouilloire finit un peu plus tôt." },
          "fr-CA": { categoryTitle: "Bouilloire", prompt: "Le point d'ébullition de l'eau au niveau de la mer, en Celsius, c'est quoi ?", choices: ["100", "90", "80", "120"], banterHint: "En montagne, la bouilloire finit un peu plus tôt." },
          de: { categoryTitle: "Kessel", prompt: "Wie hoch ist der Siedepunkt von Wasser auf Meereshöhe, in Celsius?", choices: ["100", "90", "80", "120"], banterHint: "Auf dem Berg ist der Kessel etwas früher fertig." },
        },
      }),
      q({
        id: "cq-h-multi-photo",
        tier: "hard",
        topic: "current-culture",
        generation: "multi-gen",
        correctIndex: 2,
        sources: [{ label: "Encyclopaedia Britannica — photosynthesis" }, { label: "NASA Earth Observatory — carbon cycle" }],
        text: {
          en: { categoryTitle: "Green Work", prompt: "Which gas do plants take in during photosynthesis?", choices: ["Oxygen", "Nitrogen", "Carbon dioxide", "Helium"], banterHint: "They hand oxygen back to the room." },
          fr: { categoryTitle: "Travail vert", prompt: "Quel gaz les plantes absorbent-elles pendant la photosynthèse ?", choices: ["L'oxygène", "L'azote", "Le dioxyde de carbone", "L'hélium"], banterHint: "Elles rendent l'oxygène à la pièce." },
          "fr-CA": { categoryTitle: "Travail vert", prompt: "Quel gaz les plantes prennent pendant la photosynthèse ?", choices: ["L'oxygène", "L'azote", "Le dioxyde de carbone", "L'hélium"], banterHint: "Elles redonnent l'oxygène à la pièce." },
          de: { categoryTitle: "Grüne Arbeit", prompt: "Welches Gas nehmen Pflanzen bei der Fotosynthese auf?", choices: ["Sauerstoff", "Stickstoff", "Kohlenstoffdioxid", "Helium"], banterHint: "Sauerstoff geben sie dem Raum zurück." },
        },
      }),
      q({
        id: "cq-h-multi-pitch",
        tier: "hard",
        topic: "current-culture",
        generation: "multi-gen",
        correctIndex: 1,
        sources: [{ label: "FIFA — laws of the game" }, { label: "Encyclopaedia Britannica — football" }],
        text: {
          en: { categoryTitle: "On the Field", prompt: "How many players from one soccer team are on the field at a time?", choices: ["9", "11", "13", "15"], banterHint: "The goalkeeper counts as one of them." },
          fr: { categoryTitle: "Sur le terrain", prompt: "Combien de joueurs d'une équipe de football sont sur le terrain en même temps ?", choices: ["9", "11", "13", "15"], banterHint: "Le gardien compte parmi eux." },
          "fr-CA": { categoryTitle: "Sur le terrain", prompt: "Combien de joueurs d'une équipe de soccer sont sur le terrain en même temps ?", choices: ["9", "11", "13", "15"], banterHint: "Le gardien compte parmi eux." },
          de: { categoryTitle: "Auf dem Platz", prompt: "Wie viele Spieler einer Fußballmannschaft stehen gleichzeitig auf dem Feld?", choices: ["9", "11", "13", "15"], banterHint: "Der Torwart zählt mit." },
        },
      }),
      q({
        id: "cq-h-multi-compass",
        tier: "hard",
        topic: "current-culture",
        generation: "multi-gen",
        funny: true,
        technique: "misdirection",
        structure: "joke",
        correctIndex: 0,
        text: {
          en: { categoryTitle: "True North", prompt: "Why did the compass join the quiz?", choices: ["It wanted to get its bearings", "It hid the map", "It lost the needle", "It skipped the trail"], banterHint: "North stayed a kind direction." },
          fr: { categoryTitle: "Plein nord", prompt: "Pourquoi la boussole a-t-elle rejoint le quiz ?", choices: ["Elle voulait trouver ses repères", "Elle a caché la carte", "Elle a perdu l'aiguille", "Elle a sauté le sentier"], banterHint: "Le nord est resté une direction gentille." },
          "fr-CA": { categoryTitle: "Plein nord", prompt: "Pourquoi la boussole s'est jointe au quiz ?", choices: ["Elle voulait trouver ses repères", "Elle a caché la carte", "Elle a perdu l'aiguille", "Elle a sauté le sentier"], banterHint: "Le nord est resté une direction gentille." },
          de: { categoryTitle: "Kurs Nord", prompt: "Warum trat der Kompass dem Quiz bei?", choices: ["Er wollte sich orientieren", "Er versteckte die Karte", "Er verlor die Nadel", "Er übersprang den Weg"], banterHint: "Norden blieb eine freundliche Richtung." },
        },
      }),
      q({
        id: "cq-h-multi-eclipse",
        tier: "hard",
        topic: "current-culture",
        generation: "multi-gen",
        structure: "colour",
        correctIndex: 0,
        sources: [{ label: "NASA — lunar eclipse" }, { label: "Encyclopaedia Britannica — eclipse" }],
        text: {
          en: { categoryTitle: "Night Shade", prompt: "What colour is the Moon during a total lunar eclipse?", choices: ["Red", "Blue", "Green", "White"], banterHint: "Earth's shadow lends that shade." },
          fr: { categoryTitle: "Teinte de nuit", prompt: "De quelle couleur est la Lune pendant une éclipse lunaire totale ?", choices: ["Rouge", "Bleu", "Vert", "Blanc"], banterHint: "L'ombre de la Terre prête cette teinte." },
          "fr-CA": { categoryTitle: "Teinte de nuit", prompt: "C'est quoi la couleur de la Lune pendant une éclipse lunaire totale ?", choices: ["Rouge", "Bleu", "Vert", "Blanc"], banterHint: "L'ombre de la Terre prête cette teinte." },
          de: { categoryTitle: "Nachtton", prompt: "Welche Farbe hat der Mond während einer totalen Mondfinsternis?", choices: ["Rot", "Blau", "Grün", "Weiß"], banterHint: "Der Schatten der Erde leiht diesen Ton." },
        },
      }),
    ],
  },
];

export function creatorQuestions(locale = "en") {
  const out = [];
  for (const creator of CREATORS) {
    for (const row of creator.questions) {
      const flat = translateQuestion(row, locale);
      if (flat) out.push(flat);
    }
  }
  return out;
}
